### ISSUE TITLE
Cannot fetch artifact from google storage based maven repo

### ISSUE THREAD

**Issue by ramzimaalej** [gradle/gradle#10835]
I use google storage as a maven repository to host internal artifacts. When using Maven, I'm able to push and load artifacts from it. However, when using gradle, I'm not able to load artifacts from it. 

I get this error: Required parameter bucket must be specified.

my url is like this gcs://infra_xxxxxx/maven/release

A similar issue has been reported here, but with no response: 
https://discuss.gradle.org/t/google-cloud-storage-backed-maven/27434/4
https://discuss.gradle.org/t/issue-using-gcs-as-a-maven-repository/32075

**Comment by ramzimaalej** [comment]
I think this is the culprit: https://github.com/gradle/gradle/blob/e975872ae2cf1d521b73f1107cae772ca09c63cd/subprojects/resources/src/main/java/org/gradle/internal/resource/ExternalResourceName.java#L83

It' stripping off the bucket name from the url.

**Comment by ljacomet** [comment]
Thanks for the report. Seeing that you have done some analysis, care to share the train of thought that leads you to blame the method you linked?

**Comment by ramzimaalej** [comment]
This is what I did: I instantiated this class and called encodeRoot with this URI: gcs://ramzimaalej/maven/release

I ended up with gcs://maven/release the same thing that I see in my logs. 

I will report back after I test with a gradle version I built from the source

**Comment by jjohannes** [comment]
@ramzimaalej I remember trouble with that class. And indeed it looks like I fixed something related there last year: https://github.com/gradle/gradle/commit/431b2f0c0b9a2f75c40d13d9d8c347842d63df1f

Maybe this `isFileOnHost` check is too narrow:
https://github.com/gradle/gradle/blob/431b2f0c0b9a2f75c40d13d9d8c347842d63df1f/subprojects/resources/src/main/java/org/gradle/internal/resource/ExternalResourceName.java#L72-L74

If you are building from source, you can maybe try and possibly even provide a PR. :)
If you have a test case, you can add it to `ExternalResourceNameTest`.

**Comment by jjohannes** [comment]
We did not hear back and the assumption I made about how to fix this was wrong. We actually have tests that show that this is working. Only that the tests do not use a real GCS but a test fixture emulating it (and there we might miss something).

@qiwenzhao Can you reproduce this issue with Gradle `6.0.1` and if, can you sent some more information about the error you are seeing? (stack trace or better build scan)

**Comment by qiwenzhao** [comment]
Thanks getting back to me. I will collect the info and post back.

**Comment by qiwenzhao** [comment]
Here are the info:

------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.4 (Oracle Corporation 11.0.4+10-LTS)
OS:           Mac OS X 10.15.1 x86_64

maven {
       url "gcs://maven_repo_kevin"
}
(I put the com/... at the root of the bucket).

The error:

Could not get resource 'gcs:/com....'
Required parameter bucket must be specified.

**Comment by qiwenzhao** [comment]
I don't have system setup to build gradle yet, from my observation, it seems that it striped out 

//bucket_name before passing into 

https://github.com/eleventigerssc/gradle/blob/40bd85e6568843654273b47a271a18b467120331/subprojects/resources-gcs/src/main/java/org/gradle/internal/resource/transport/gcs/GcsClient.java

So the url ends up like:

gcs:/.../...

Which URI.getHost() fails to extract the bucket name.

**Comment by jjohannes** [comment]
@qiwenzhao Thanks. Looking again, I realized that we miss some very basic test coverage. From what I can see, this works if you already have something in your cache (e.g. in maven local). But not for the plain case were you are retrieving the module for the first time.

Fix: #11669

**Comment by qiwenzhao** [comment]
Thanks for the quick fix.

**Comment by jjohannes** [comment]
@qiwenzhao can you confirm that the issue is fixed for you in the latest 6.1 nightly (`20191217025822+0000)?`

**Comment by qiwenzhao** [comment]
sorry for the slow response, missed the notification, I tried this:

./gradlew wrapper --gradle-version=6.1-20191217025822+0000

but still getting the same error:

Could not get resource 'gcs:/consumer/...'

Required parameter bucket must be specified.
maven {
            url "gcs://maven_repo_kevin/consumer"
        }

This is an android project, it still has the 

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
    }

in build.gradle. I am wondering if it is not picking up the new version

**Comment by jjohannes** [comment]
Thanks for testing @qiwenzhao.

🤔 Maybe there is another code path / state I missed. Can you double check that you actually got the change by testing again with 6.1 RC1 which was just release?

> classpath 'com.android.tools.build:gradle:3.4.2'

That is the Android plugin for Gradle. The version is unrelated to the Gradle version.

If you want to make sure you got the right Gradle version, please run from the command line:

`./gradlew --version`

And then test if your build works also from the command line:

`./gradlew assembleDebug`

**Comment by qiwenzhao** [comment]
------------------------------------------------------------
Gradle 6.1-20191217025822+0000
------------------------------------------------------------

Build time:   2019-12-17 02:58:22 UTC
Revision:     387c1afbf8248935f4bd37e0d1be0a49cf6d1ccc

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.4 (Oracle Corporation 11.0.4+10-LTS)
OS:           Mac OS X 10.15.2 x86_64

./gradlew assembleDebug

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileStagingDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':stagingDebugCompileClasspath'.
   > Could not resolve com.....:0.8.4.
     Required by:
         project :
      > Could not resolve com....r:0.8.4.
         > Could not get resource 'gcs:/consumer/com/....pom'.
            > Required parameter bucket must be specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1-20191217025822+0000/userguide/command_line_interface.html#sec:command_line_warnings

Ok, from this, it does confirm the version is correct. 

Thanks for looking into this.

**Comment by jjohannes** [comment]
> Could not get resource 'gcs:/consumer/com/....pom'.

@qiwenzhao I think you are missing a `/` there. It should be `gcs://` for the schema.

So `gcs:/consumer/...` should be `gcs://consumer/...`

**Comment by qiwenzhao** [comment]
That is the error message, my maven url is actually:

maven {
            url "gcs://maven_repo_kevin/consumer"
}

So the message is showing before the url get passed in to the place you changed,  it has already been changed to

gcs:/consumer/

**Comment by ramzimaalej** [comment]
Sorry for the delayed response. 

Here are my changes that made it work for me. I hope this helps.


[Fix_loading_gcs_resources.txt](https://github.com/gradle/gradle/files/3992918/Fix_loading_gcs_resources.txt)

**Comment by jjohannes** [comment]
Thanks @qiwenzhao for clarification. I am not able to reproduce this problem with the fix. Any chance you can provide a full build script that reproduces the issue? Maybe it is something specific to how you declare the dependencies?

This build script works in our tests (`6.1-rc-1`):

```
repositories {
    maven {
        url "gcs://testGcsbucket/maven/release"
    }
}

configurations { compile }

dependencies{
    compile 'org.gradle:test:1.85' // module published in the GCS repo
}

task retrieve(type: Sync) {
    from configurations.compile
    into 'libs'
}
```

**./gradlew retrieve**

**Comment by jjohannes** [comment]
Thanks @ramzimaalej for sharing your fix. Is the issue fixed for you in `6.1-rc-1`?

**Comment by ramzimaalej** [comment]
@jjohannes Unfortunately, it does not work. Here is what I get:

` Could not get resource 'gcs:/maven/release/
 Required parameter bucket must be specified.
`

**Comment by jjohannes** [comment]
Thanks for getting back @ramzimaalej. I am at a loss. If I apply your patch, our tests are failing because the bucket name is duplicated. This must be something environment specific. Although I have pretty much the same setup as here https://github.com/gradle/gradle/issues/10835#issuecomment-567939779 and we also run the tests on different machines and Java versions.

@ramzimaalej  @qiwenzhao Could you both help me:

Run the very simple build I showed here https://github.com/gradle/gradle/issues/10835#issuecomment-570142913 locally with `--scan` and send me the build scan link?
