### ISSUE TITLE
Gradle logs a non-fatal error message with FindBugs

### ISSUE THREAD

**Issue by wujek-srujek** [gradle/gradle#1094]
When built with Gradle 3.3, findbugs reports the following (please note the build works fine, it is just the output is very confusing):

      :findbugsMain
      Scanning archives (34 / 34)
      2 analysis passes to perform
      Pass 1: Analyzing classes (12 / 12) - 100% complete
      Pass 2: Analyzing classes (1 / 1) - 100% complete
      Done with analysis
      The following errors occurred during analysis:
        Cannot open codebase filesystem:/Users/wujek/Development/IdeaProjects/gradle-test/build/classes/main/META-INF/spring-configuration-metadata.json
          java.io.IOException: Wrong magic bytes of 7b0a2020 for zip file /Users/wujek/Development/IdeaProjects/gradle-test/build/classes/main/META-INF/spring-configuration-metadata.json of 255 bytes
            At edu.umd.cs.findbugs.classfile.impl.ZipFileCodeBase.<init>(ZipFileCodeBase.java:87)
            At edu.umd.cs.findbugs.classfile.impl.ZipCodeBaseFactory.makeZipCodeBase(ZipCodeBaseFactory.java:39)
            At edu.umd.cs.findbugs.classfile.impl.ClassFactory.createFilesystemCodeBase(ClassFactory.java:121)
            At edu.umd.cs.findbugs.classfile.impl.FilesystemCodeBaseLocator.openCodeBase(FilesystemCodeBaseLocator.java:77)
            At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.processWorkList(ClassPathBuilder.java:607)
            At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:226)
            At edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:677)
            At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:218)
            At org.gradle.api.plugins.quality.internal.findbugs.FindBugsExecuter.runFindbugs(FindBugsExecuter.java:39)
            At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            At java.lang.reflect.Method.invoke(Method.java:498)
            At org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:87)
            At org.gradle.process.internal.worker.request.WorkerAction.runThenStop(WorkerAction.java:71)
            At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            At java.lang.reflect.Method.invoke(Method.java:498)
            At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
            At org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
            At org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
            At org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
            At org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
            At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            At java.lang.Thread.run(Thread.java:745)

This doesn't happen when built with Gradle 3.2.

The issue seems to be that Spring Boot configuration processor creates a JSON file in build/classes/main/META-INF/, and findbugs attempts to open it as a ZIP file, and fails.

### Expected Behavior
Just like in Gradle 3.2, the error is not printed out.

### Current Behavior
An error is printed out, but the build works fine nonetheless, making things confusing.

### Steps to Reproduce (for bugs)
The project showing the issue is here: https://github.com/wujek-srujek/gradle-3.3-boot-findbugs.
1. Clone the repository.
2. Check out the 'gradle-3.2' tag.
3. Invoke './gradlew' - the build works fine, no issues.
4. Check out the 'gradle-3.3' tag.
5. Invoke './gradlew' again - this time the aforementioned error is seen in the output.

### Your Environment
    $ java -version
    java version "1.8.0_102"
    Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
    $ uname -a
    Darwin Laptop0158 14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu- 2782.50.9~1/RELEASE_X86_64 x86_64

**Comment by timx9** [comment]
I get a similar problem with 3.3 - findbugs tries to open binary files in the project - see attached build output
[build.txt](https://github.com/gradle/gradle/files/695889/build.txt)

The problem is not present in 3.2

**Comment by big-guy** [comment]
This is due to some logging changes introduced in 3.3 so we can see output from forked worker processes (like FindBugs): https://github.com/gradle/gradle/pull/970

This has been happening for awhile (you can see it in 3.2), but the message was only shown at the `--debug` level.  That stacktrace/exception is logged by FindBugs on stderr.  

It looks like the underlying problem is that the classpath that FindBugs is trying to analyze has non-class/jar files in it.  I haven't looked deeply to know if this is something we can fix.

**Comment by ddimtirov** [comment]
That is also a problem for Kotlin 1.0.6+ which generates modules files in META-INF.
See https://youtrack.jetbrains.com/issue/KT-15728

**Comment by jeserkin** [comment]
Can anyone confirm, that it is present in version: '3.0.1'?

**Comment by dinomite** [comment]
@jeserkin I can, using Gradle 3.5 with Findbugs 3.0.1.  (also, incidentally, I'm using Kotlin 1.1.2-2)

**Comment by jeserkin** [comment]
Okay. I have same setup. Any solution for that issue?

**Comment by ddimtirov** [comment]
The upcoming Gradle 4.0 will separate the output dirs for Kotlin and Java compilers. Then the Findbugs will only check the Java classes.

**Comment by henrik242** [comment]
We have the same problem on 3.5.  Not using Kotlin.

**Comment by wolfs** [comment]
This has been fixed by #2102 and the fix will be included in 4.0 RC1. @wujek-srujek Could you confirm that your problem is fixed by trying out the latest Gradle nightly build?

**Comment by wujek-srujek** [comment]
I confirm 4.0-rc-1 fixes the issue for me.

I was away on holiday with a very dodgy internet connection, couldn't test it sooner, sorry.

**Comment by ryonday** [comment]
This is still happening to me with 4.2.1. Is this a configuration issue on my side?
