### ISSUE TITLE
Kotlin Android project fails with java11/java13

### ISSUE THREAD

**Issue by jmfayard** [gradle/gradle#11084]
### Expected Behavior

I have a simple Android Studio (AGP 3.5.1) + Kotlin (1.3.50) project that works fine with Gradle 5.6.2

I expect `./gradlew $TASK` to continue to work after I upgrade to gradle 6.0-rc-1 and Java13

Not sure if it's a bug from Gradle, Jetbrains, Android or all of them.

### Current Behavior

```
$ ./gradlew --scan dependencies                                                                                                                                                    
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > wrong number of arguments
   > KotlinJvmAndroidCompilation with name 'debugAndroidTest' not found.

Publishing build scan...
https://gradle.com/s/yjwfqdw2ysrlk
```

### Context

Fails in Gradle 6.0-rc-1 with Java13 and Kotlin 1.3.50 and AGP 5.3.1

Works if I use Java 8 and Gradle 5.6.2

### Steps to Reproduce 

1) git clone the `gradle6` branch here

https://github.com/jmfayard/update-legacy-android-project/tree/gradle6

2) run `./gradlew --scan dependencies`

                                                                                                                                                   

### Your Environment

- plugin("android").version("3.5.1")
- plugin("org.jetbrains.kotlin.android").version("1.3.50")
- Operating system	Mac OS X 10.15
- Java runtime	AdoptOpenJDK OpenJDK Runtime Environment 13+33

Build scan URL: https://gradle.com/s/yjwfqdw2ysrlk

**Comment by big-guy** [comment]
Does it fail with Java 8 + 6.0-rc-1?

**Comment by big-guy** [comment]
I'm not seeing a failure with JDK11 or JDK13 and 6.0-rc-1 with your branch when running `gradle help` or `gradle dependencies`.

> id("com.louiscad.splitties").version("0.1.0")

This doesn't appear to be published and is coming from your ~/.m2.  Is it possible it has something funky in it?

**Comment by LouisCAD** [comment]
I have to publish the plugin to gradle portal, but I'm seeing an issue for now, that I'm looking with Gradle folks to get resolved:
```
> Failed to post to server.
  Server responded with:
  You are not the owner of group com.louiscad.splitties
```
(happened after ownership transfer)

**Comment by LouisCAD** [comment]
@big-guy The plugin publishing issue has been resolved since then, the project should work on your side now.

**Comment by big-guy** [comment]
@LouisCAD Thanks, I'm still not seeing a failure.  Is there maybe something else that's different?  Does it not fail with JDK8 for you?

**Comment by jjohannes** [comment]
I have looked at this again. I can't reproduce the original error so I was digging a bit through the build scan and the stack trace in it. The failure is thrown when `NamedDomainObjectProvider.get()` is invoked reflectively within the Kotlin Gradle plugin. It is a weird error and I can't really see how that can happen unless there is a buggy behavior in the used Java RT or the classpath of the build itself is somehow _screwed up_. Some things in the build scan that might indicate this:

- `com.android.tools.build:gradle:3.1.3` (not 3.5.1) on [the root build classpath](https://scans.gradle.com/s/yjwfqdw2ysrlk/build-dependencies?toggled=W1sxXSxbMF0sWzAsMF0sWzAsMCxbMTgxXV1d)
- `AdoptOpenJDK OpenJDK Runtime Environment 13+33` Java runtime VS `	Eclipse OpenJ9 Eclipse OpenJ9 VM openj9-0.16.0 (JRE 13 ...` JVM - 
https://scans.gradle.com/s/yjwfqdw2ysrlk#infrastructure

As I can't reproduce, I can't debug this further. With the current knowledge, I doubt that this is a regression in Gradle from 5.6.3 -> 6.0 or a specific issue with Gradle's Java13 support. I assume there is somethign fishy in the setup and the appearance of the error might depend on the (build) classpath order.

@jmfayard I also didn't see the `gradle6` branch in your example anymore. Did you remove that on purpose? Are you still able to reproduce this issue?

**Comment by jmfayard** [comment]
Hello @jjohannes 

I tried with different versions of Gradle + Java switching with https://sdkman.io/

- This commit works with Gradle 6 https://github.com/jmfayard/buildSrcVersions/commit/8681484d6446a182a281e6e11cb8be812dd17624
- This commit works with Gradle 5.6.3 https://github.com/jmfayard/buildSrcVersions/commit/648a4051f4e3e2a639f55ec7d6be0a5c8ff63e02

I have found that

- Gradle 5 + Java 8 works
- Gradle 5 + Java 11 doesn't work https://scans.gradle.com/s/4xe6vb75zwiha
- Gradle 5 + Java 13 doesn't work (no Gradle support obviously)
- Gradle 6 + Java 8 works 
- Gradle 6 + Java 13 doesn't work  https://gradle.com/s/dc3nq6nxekutu

**Comment by jmfayard** [comment]
@big-guy correct, the plugin was not published. 
This can now be tested with the two commits I have indicated in my previous comment ^^

**Comment by DRSchlaubi** [comment]
The strange thing is for me the build only runs on Jetbrains runtime 11

**Comment by hingbong** [comment]
can't build apk on openj9 jdk which use less memory, my laptop has less RAM

**Comment by minsko** [comment]
I encountered a similar issue with AGP 4.0.0, Gradle v6.1.1, andEclipse OpenJ9 VM v1.8.0_242.
Upgrading to use Gradle v6.2.2 fixed it for me.

**Comment by dennismayr** [comment]
> I encountered a similar issue with AGP 4.0.0, Gradle v6.1.1, and Eclipse OpenJ9 VM v1.8.0_242.
> Upgrading to use Gradle v6.2.2 fixed it for me.

This did the trick.

Apparently, it's a known issue that should be addressed soon
https://github.com/AdoptOpenJDK/openjdk-support/issues/127

**Comment by jjohannes** [comment]
Closing as it looks fixed with the right combination of tools.
