### ISSUE TITLE
Published POMs using the `maven-publish` plugin have "runtime" for all dependency scopes

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#1118]
All dependencies in the generated POM have scope `runtime

### Expected Behavior

Dependencies should have the appropriate scope.

### Current Behavior

- https://stackoverflow.com/questions/20131915/publishing-artifact-from-gradle-project-to-bintray-maven-repository
- https://discuss.gradle.org/t/maven-publish-plugin-generated-pom-making-dependency-scope-runtime/7494/12

### Context

Transitive dependencies are not included on the compile classpath for consumers of JAR's published this way.

### Steps to Reproduce (for bugs)

1. Add the `java` plugin and `maven-publish` plugin
1. Add some `dependencies` with `compile` and `runtime` scopes
1. Configure a `MavenPublication` with `components.java`
1. Run a `publishToMavenLocal`
1. See that the published POM has all `runtime` scoped dependencies

### Your Environment

 * Build scan URL:

**Comment by mkobit** [comment]
Here is a possible workaround that I haven't tried from https://gist.github.com/bugs84/b7887fb5d7f9f2d484b8#file-changefromruntimetocompile-gradle:

```groovy
publishing.publications.all {
  pom.withXml {
    asNode().dependencies.'*'.findAll() {
      it.scope.text() == 'runtime' && project.configurations.compile.allDependencies.find { dep ->
        dep.name == it.artifactId.text()
      }
    }.each { it.scope*.value = 'compile'}
  }
}
```

**Comment by oehme** [comment]
This is a modeling problem which we are currently addressing. `compile` currently contains two things: My API dependencies as well as my implementation dependencies. Only the API dependencies should be marked with Mavens `compile` scope, which exports them to consumers. 

We will add api/implementation dependency separation in Gradle 3.4. The maven-publish plugin will be changed to correctly handle those.

**Comment by oehme** [comment]
This has been fixed in Gradle 3.4 with the `java-library` plugin. All `api` dependencies are marked as `compile` while `implementation` dependencies are marked as `runtime`.

**Comment by hanasaki** [comment]
still seeing this issue in gradle 4.7
note: the pom created by publishToMavenLocal is full of runtime however the pom produced with task createPom { pom ....   is correct.     
1. is there a way to make publishToMavenLocal use the pom my task creates instead of the "default"?
2. in 4.7 this does not seem fixed. IMHO

**Comment by oehme** [comment]
Please make sure you are using `api`/`implementation`, not `compile/runtime` for your dependency declarations.

**Comment by osipxd** [comment]
I have same problem as @hanasaki in this project: https://gitlab.com/endlesscodegroup/inspector

I have two modules `inspector-bukkit` and `inspector-common`. bukkit module depends on common with `api` configuration, but in pom.xml I have `runtime` scope for `inspector-common` dependency.

**Comment by marcphilipp** [comment]
@osipxd That's due to a bug in the Kotlin plugin: https://youtrack.jetbrains.com/issue/KT-28355

**Comment by osipxd** [comment]
@marcphilipp, thanks. I'll track it
