### ISSUE TITLE
PMD Exception: Could not determine if Stdout is a console: could not get handle file information (errno 1)

### ISSUE THREAD

**Issue by thumannw** [gradle/gradle#11205]
### Expected Behavior
Invoking PMD via the pmd plugin should not throw unexpected exceptions.

### Current Behavior
Sporadically, the Pmd task throws the following NativeException:
```
Caused by: net.rubygrapefruit.platform.NativeException: Could not determine if Stdout is a console: could not get handle file information (errno 1)
	at net.rubygrapefruit.platform.internal.WindowsTerminals.getTypeForOutput(WindowsTerminals.java:68)
	at net.rubygrapefruit.platform.internal.WindowsTerminals.isTerminal(WindowsTerminals.java:27)
	at org.gradle.internal.nativeintegration.console.NativePlatformConsoleDetector.getConsole(NativePlatformConsoleDetector.java:41)
	at org.gradle.internal.nativeintegration.console.TestOverrideConsoleDetector.getConsole(TestOverrideConsoleDetector.java:38)
	at org.gradle.api.plugins.quality.Pmd.stdOutIsAttachedToTerminal(Pmd.java:99)
	at org.gradle.api.plugins.quality.Pmd$stdOutIsAttachedToTerminal.call(Unknown Source)
	at org.gradle.api.plugins.quality.internal.PmdInvoker.invoke(PmdInvoker.groovy:44)
	at org.gradle.api.plugins.quality.Pmd.run(Pmd.java:94)
```

### Context
The pmd plugin is applied to a buildscript in order to perform static code analysis in a CI environment. When the sporadic exception occurs, the build fails and needs to be retriggered. This behavior has also been reported on the [Gradle Forum](https://discuss.gradle.org/t/pmdmain-fails-on-gradle-5-4-1-could-not-determine-if-stdout-is-a-console-could-not-get-handle-file-information-errno-1/31588).

### Steps to Reproduce 
Hard to reproduce. Seems to be a timing issue in a Windows native method call _net.rubygrapefruit.platform.internal.jni.WindowsConsoleFunctions::isConsole_. The native error result is "could not get handle file information (errno 1)".
Attached a minimal [pmd project](https://github.com/gradle/gradle/files/3800989/pmd.zip).

### Your Environment
Windows version: 10.0.17134
Gradle version: 5.6.2
Java version: Amazon Coretto 8.222.10.3
More environments in the [Gradle Forum topic](https://discuss.gradle.org/t/pmdmain-fails-on-gradle-5-4-1-could-not-determine-if-stdout-is-a-console-could-not-get-handle-file-information-errno-1/31588).

**Comment by lacasseio** [comment]
Although the suggested PR makes a lot of sense for what needs to be achieved, it looks like there is an issue with the NativePlatform for a very specific case. The error is happening when the STDOUT is passed to [GetFileInformationByHandleEx is called](https://github.com/adammurdoch/native-platform/blob/master/src/main/cpp/win.cpp#L652) when trying to determine if it's a Cygwin or msys STDOUT pipe. The error returned is [0x1 `ERROR_INVALID_FUNCTION`](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-) which is an incorrect function. It seems this issue happen on pre-vista or if the underlying driver would not support this function.

There is a couple follow up question we should ask before:
1- Is Gradle running inside a Cygwin or msys shell? Or Windows Linux Subsystem?
2- Is the STDOUT/STDERR pipe redirected in any way to a file on disk? If so, where is the file being written (e.g. NFS server, NTFS drive, RAM drive, etc)?
3- Who is calling Gradle? A human at the command line or Jenkins or something else?
4- Is Gradle running inside a container? Is it a Windows or Linux container?
5- Is the output redirected to `/dev/null` or `NUL`?

**Comment by lacasseio** [comment]
Also is it possible to try Gradle 6.0 to see if the issue still appears?

**Comment by lacasseio** [comment]
If you are using Cygwin or msys, could you tell me the version, most likely using `uname -r`.

**Comment by lacasseio** [comment]
It seems this may be an issue in [native platform](https://github.com/adammurdoch/native-platform/issues/43) instead.

**Comment by thumannw** [comment]
1. Powershell 5.1 on Windows 10.0.17134
2. no redirection to file
3. human via Powershell, but happened also on Jenkins via a "bat" call in the Jenkinsfile
4. no container
5. no redirection

**Comment by lacasseio** [comment]
Thanks for the information. We merged PR to make the PMD task more resilient to exception. Give it a try in the next nightly. It will be part of Gradle 6.1.

**Comment by jskovjyskebankdk** [comment]
I still see the problem (with Gradle 6.1 RC1).

It is in a rather weird context, granted, but I would really like it to work:
I use a Gradle Exec task to run a bat script with Wine.
This script starts another (windows) Gradle. And this (inner instance) fails with the bug title message.

(both using gradlew with --no-daemon)

I use it to "cross-compile" a jpackage build for Windows from a Linux box.

Unfortunately, I cannot get the inner gradle to create the stack trace (with -s), it also does not respect the "--console plain" argument.

The build works when run native, and when run from wine. The problem only occurs when running "gradle from wine from gradle" :)

I have tried adding to gradle.properties:
    gradle.startParameter.showStacktrace = org.gradle.api.logging.configuration.ShowStacktrace.ALWAYS

But it also does not have any effect.


I am open for ideas about how to provide you with more specific information about the problem.
