### ISSUE TITLE
Delegated build process always triggers Spring-Boot devtools restart

### ISSUE THREAD

**Issue by Dazzel** [gradle/gradle#12220]
When using an IDE such IDEA and the build process is delegated to grade (default behaviour) the devtools are always triggering a restart even if only "reload-resources" are modified.

### Expected Behavior
The build process, especially `:processResources` task should only copy modified resources to the output, thus not triggering an complete restart.

### Current Behavior
The `:processResources` task is always cleaning the output first and copies all, even unmodified, files.

### Context
Spring devtools are designed to make the development easier by utilizing an sophisticated restart / reload process. For example if you modify only templates (.html) the tool will detect the changes, put them into the running application BUT no restart is triggered. Changing other resources like java classes the application is restarted to reflect the changes.

An issue was already raised in the [spring-boot project](https://github.com/spring-projects/spring-boot/issues/20136).

### Steps to Reproduce 
Demo project is available in the linked issue. Otherwise simply create an demo project with the Spring initializr with dependencies like (web, thymeleaf, lombok) and modify templates.

### Your Environment
Spring Boot version: 2.2.4.RELEASE
Gradle version: 6.0.1
IntelliJ IDEA: 2019.3

Build scan URL (clean build): https://scans.gradle.com/s/amxh5awsxljsu
Build scan URL (rebuild): https://scans.gradle.com/s/fchmwc27onjuk

**Comment by wilkinsona** [comment]
This continues to be a problem for Spring Boot users who use Devtools and IntelliJ IDEA. It would be useful to know if there's a possibility of this being fixed in Gradle, for example by making process resources more fine-grained so that it doesn't need to clean its output location on each invocation.

**Comment by Dazzel** [comment]
Also still reproducible with the newest Gradle and IntelliJ IDEA versions. Switching to the IntelliJ based build process is not really feasible when the process gets a bit more complicated or involves extra steps - even the configuration of annotation processors gets wonky when using both systems instead of only Gradle (different classpaths, build outouts, generated paths, etc.).

**Comment by ljacomet** [comment]
This requires making the `Copy` task of Gradle incremental, which it is not for the moment.
This is unlikely to happen in the short or medium term.
