### ISSUE TITLE
Unable to exclude kotlin file in javaDir with Kotlin DSL

### ISSUE THREAD

**Issue by creasexul** [gradle/gradle#12790]
### Code
```
    sourceSets {
        getByName("main") {

            java.srcDirs("src/main/kotlin")

            withConvention(KotlinSourceSet::class) {
                kotlin.srcDir("src/main/kotlin")
                kotlin.exclude("**/ExampleExcludeKotlinClass.kt")
            }

        }
    }
```

### Expected Behavior
When generate apk, this file(ExampleExcludeKotlinClass) will be exclude from apk.

### Current Behavior
This file is still packaged into apk.
If I remove these code ` java.srcDirs("src/main/kotlin")`, it works but ide will not add these class into build tree.

### Context
Try to use different flavors to package different apks with some different changes(not the same function).

### Steps to Reproduce (for bugs)
[example](https://github.com/creasexul/RouteReplaceHelper)

### Your Environment
* Gradle version: 6.3-all
* Android Studio version: Android Studio 3.6.1
* Kotlin Plugin version: 1.3.61

**Comment by creasexul** [comment]
Has anyone have an idea ?

**Comment by creasexul** [comment]
Knock, knock..

**Comment by shawnthye-razer** [comment]
Knock Knock...

**Comment by St4B** [comment]
Do we know if this issue is planned to be solved?

**Comment by SMAXLYB** [comment]
how to slove this?

**Comment by HuangJAndroid** [comment]
> ### Code
> ```
>     sourceSets {
>         getByName("main") {
> 
>             java.srcDirs("src/main/kotlin")
> 
>             withConvention(KotlinSourceSet::class) {
>                 kotlin.srcDir("src/main/kotlin")
>                 kotlin.exclude("**/ExampleExcludeKotlinClass.kt")
>             }
> 
>         }
>     }
> ```
> 
> ### Expected Behavior
> When generate apk, this file(ExampleExcludeKotlinClass) will be exclude from apk.
> 
> ### Current Behavior
> This file is still packaged into apk. If I remove these code , it works but ide will not add these class into build tree.` java.srcDirs("src/main/kotlin")`
> 
> ### Context
> Try to use different flavors to package different apks with some different changes(not the same function).
> 
> ### Steps to Reproduce (for bugs)
> [example](https://github.com/creasexul/RouteReplaceHelper)
> 
> ### Your Environment
> * Gradle version: 6.3-all
> * Android Studio version: Android Studio 3.6.1
> * Kotlin Plugin version: 1.3.61

how to solve this?

**Comment by creasexul** [comment]
Fixed by custom gradle task when project building.

HuangJAndroid ***@***.***> 于2022年6月21日周二 11:52写道：

**Comment by HuangJAndroid** [comment]
Thank you.
I've tried, but I still can't.
Do you have any codes for reference?

**Comment by creasexul** [comment]
You can use different build types to avoid this. Just like:
```
    buildTypes {
        release {}
        include {}
        exclude {}
    }
```

Then you can define the class with same directory and same classname under include folder and exclude folder.
by changing the build variant of current project in Android Studio(usually in the bottom-left side of Android Studio), you can import different file by same classname. Then you can custom different actions in different folders.

**Comment by zlrab** [comment]
I also encountered this problem, unable to exclude kotlin source files from specific flavors, has the problem been solved?

**Comment by aspic-fish** [comment]
This worked for me.
```kotlin
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    exclude("**/ExampleExcludeKotlinClass.kt")
}
```

**Comment by ov7a** [comment]
Sorry for the late reply.

Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

**Comment by ov7a** [comment]
@aspic-fish
First of all, this is a canned answer for issues like these.

Second, this issue is not an actionable item: the problem was raised as a bug, but it's not and has a solution you provided.

If you think otherwise, you can open a new issue as described in the canned answer.

**Comment by aspic-fish** [comment]
@ov7a, now it makes more sense to me. My problem with such a template answer is that it doesn't illustrate the actual reason why the issue was closed. Thanks for your clarification. So it's closed due to the header being not accurate enough. The code provided by the author still does not work, right? But it seems it used to. When I was looking for solutions back then, I found the same ones. 
[like here](https://discuss.gradle.org/t/how-to-exclude-kotlin-files-from-compiling-with-gradle/30365/2)
So whether I want to open a new issue depends on whether it is supposed to work. So is it?

**Comment by ov7a** [comment]
@aspic-fish Thank you for your feedback and sorry for the confusion.

The expected way to exclude a file from Kotlin sources is
```kotlin
sourceSets {
    main {
        kotlin {
            exclude("**/SomeFile.kt")
        }
    }
}
```

See also:
* https://docs.gradle.org/current/userguide/building_java_projects.html
* https://github.com/gradle/kotlin-dsl-samples/issues/343

Please note that both `KotlinCompile` and `KotlinSourceSet` are part of the `kotlin` plugin, which is developed by JetBrains, not Gradle.
