### ISSUE TITLE
Stack overflow in Gradle 6.4-rc-1, regression from 6.3 

### ISSUE THREAD

**Issue by DanySK** [gradle/gradle#12832]
A build using [Orchid](https://orchid.run/), working with Gradle 6.3 runs into a stack overflow with Gradle 6.4-rc1

### Expected Behavior

The pluigin works the same way as it did in Gradle 6.3.

### Current Behavior

Stack overflow internal to Gradle:
```
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitContents(DefaultConfigurableFileCollection.java:221)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.add(DefaultFileCollectionResolveContext.java:61)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.addAll(DefaultFileCollectionResolveContext.java:52)
        at org.gradle.api.internal.file.UnionFileCollection.visitContents(UnionFileCollection.java:52)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.add(DefaultFileCollectionResolveContext.java:61)
        at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:44)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.visitContents(DefaultConfigurableFileCollection.java:297)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitContents(DefaultConfigurableFileCollection.java:221)

```

### Context

The plugin leverages Gradle to generate documentation sites.

### Steps to Reproduce 
```bash
git clone git@github.com:AlchemistSimulator/Alchemist.git
cd Alchemist/alchemist
git checkout origin/bump-gradle-wrapper-6.3-to-6.4-rc-1
./gradlew orchidServe
```

### Your Environment
Build scan URL: https://scans.gradle.com/s/mwjvff43bdgnm

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/12842

**Comment by jjohannes** [comment]
While #12842 fixed the issue when a `UnionFileCollection` is used, the issue remains for other variants of `CompositeFileCollection`. For example, we see it with the Spring boot plugin and the anonymous class defined in `CompositeFileCollection.filter()`.

**Comment by jjohannes** [comment]
The offending code change has been reverted for 6.4 (#12852)
