### ISSUE TITLE
Corrupt serialized resolution result/Problems reading from Binary store when executing `dependencies` tasks or build scans

### ISSUE THREAD

**Issue by tjuricek-vmware** [gradle/gradle#14220]
When executing `./gradlew dependencies --write-locks`, the build fails with this error:

```
integrationStubImplementation - Implementation only dependencies for compilation 'integrationStub' (target  (jvm)).

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencies'.
> Could not resolve all dependencies for configuration ':integrationStubImplementation'.
   > Problems reading data from Binary store in /tmp/gradle15135648821751580614.bin offset 221374 exists? true

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
1 actionable task: 1 executed

```

When attempting to generate `./gradlew dependencies --scan`, I receive this output:

```

> Task :dependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencies'.
> Could not resolve all dependencies for configuration ':integrationStubImplementation'.
   > Problems reading data from Binary store in /tmp/gradle13858920095948672727.bin offset 261444 exists? true

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 31s
1 actionable task: 1 executed

A build scan cannot be produced as an error occurred gathering build data.
Please report this problem via https://gradle.com/help/plugin and include the following via copy/paste:

----------
Gradle version: 6.6
Plugin version: 3.4

org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':integrationStubImplementation'.
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:104)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.access$000(ErrorHandlingConfigurationResolver.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:203)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.b(SourceFile:116)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.a(SourceFile:70)
        at com.gradle.scan.plugin.internal.b.f.a.h.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.b.f.a.g.a(SourceFile:149)
        at com.gradle.scan.plugin.internal.b.f.c.a(SourceFile:135)
        at com.gradle.scan.plugin.internal.j.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.j.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.j.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.j.k.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.j.c.a(SourceFile:103)
        at com.gradle.scan.plugin.internal.j.g.a(SourceFile:48)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.q.a.c(SourceFile:67)
Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /tmp/gradle13858920095948672727.bin offset 261444 exists? true
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:132)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:187)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:185)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:157)
        at org.gradle.api.internal.artifacts.result.DefaultResolutionResult.getRoot(DefaultResolutionResult.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:201)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.b(SourceFile:116)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.a(SourceFile:70)
        at com.gradle.scan.plugin.internal.b.f.a.h.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.b.f.a.g.a(SourceFile:149)
        at com.gradle.scan.plugin.internal.b.f.c.a(SourceFile:135)
        at com.gradle.scan.plugin.internal.j.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.j.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.j.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.j.k.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.j.c.a(SourceFile:103)
        at com.gradle.scan.plugin.internal.j.g.a(SourceFile:48)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.q.a.c(SourceFile:67)
Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (889) for constraint integrationStubImplementation -> com.vmware.carbonblackcloud:exekute:1.0.0
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:82)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:237)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:130)
        ... 21 more
----------

```

Could this be a weird local dependency problem?

Also, I did successfully run ` ./gradlew classes --update-locks com.vmware.carbonblackcloud:exekute`. So I'm not 100% sure if that's just a red herring here or not.

### Expected Behavior

I would like for all of my dependencies to resolve, basically, or flag an actionable error that indicates what is the problem on my end.

### Current Behavior

See the above output, it's pretty much "I can't update my lockfiles using the global command". 

### Context

We're using version locking, and I have several libraries I'm using, and I want to update all dependencies, to look for updates, typically to the AWS library.

### Steps to Reproduce 

This is challenging, because it's in a project with a whole bunch of company IP. And I can't provide a build scan for this task since that part fails, though I'm game for adding any other tasks, debugging, etc., though I bet the debug output would be ok. 

### Your Environment

Linux (Ubuntu 18.04), using JDK 14.0.2, and Gradle 6.6.

**Comment by tjuricek-vmware** [comment]
This morning, I actually removed that internal project, `exekute` that was listed in the build scan output, and removed some kotlin dependencies from the project. The scan still fails, but with a publicly available POM:

```
BUILD FAILED in 28s
1 actionable task: 1 executed

A build scan cannot be produced as an error occurred gathering build data.
Please report this problem via https://gradle.com/help/plugin and include the following via copy/paste:

----------
Gradle version: 6.6
Plugin version: 3.4

org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':integrationStubImplementation'.
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:104)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.access$000(ErrorHandlingConfigurationResolver.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:203)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.b(SourceFile:116)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.a(SourceFile:70)
        at com.gradle.scan.plugin.internal.b.f.a.h.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.b.f.a.g.a(SourceFile:149)
        at com.gradle.scan.plugin.internal.b.f.c.a(SourceFile:135)
        at com.gradle.scan.plugin.internal.j.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.j.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.j.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.j.k.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.j.c.a(SourceFile:103)
        at com.gradle.scan.plugin.internal.j.g.a(SourceFile:48)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.q.a.c(SourceFile:67)
Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /tmp/gradle1615510607535013790.bin offset 220456 exists? true
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:132)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:187)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:185)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:157)
        at org.gradle.api.internal.artifacts.result.DefaultResolutionResult.getRoot(DefaultResolutionResult.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:201)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.b(SourceFile:116)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.a(SourceFile:70)
        at com.gradle.scan.plugin.internal.b.f.a.h.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.b.f.a.g.a(SourceFile:149)
        at com.gradle.scan.plugin.internal.b.f.c.a(SourceFile:135)
        at com.gradle.scan.plugin.internal.j.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.j.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.j.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.j.k.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.j.c.a(SourceFile:103)
        at com.gradle.scan.plugin.internal.j.g.a(SourceFile:48)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.q.a.c(SourceFile:67)
Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (1650) for constraint platform-runtime -> com.rabbitmq:amqp-client:5.9.0
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:82)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:237)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:130)
        ... 21 more
----------
```

I'm still zeroing in on what triggers this. I think it may be a platform dependency in a custom source set.

**Comment by tjuricek-vmware** [comment]
I've only ironed out that it only occurs when the `--write-locks` option is enabled for the `dependencies` task. I've had to disable version locking, and everything resolves now.

**Comment by tjuricek-vmware** [comment]
Today I went through, and eventually figured out there were three transitive dependencies that had to be declared as `implementation` dependencies in the main source set, and that bypassed the resolution problems. I can't for the life of me, understand what these had to do with anything, I suspect it's just a hidden timing issue. 

It makes no sense otherwise that these dependencies would have caused any particular harm:

```
implementation("com.rabbitmq:amqp-client:5.9.0")
implementation("net.bytebuddy:byte-buddy-agent:1.10.13")
implementation("commons-logging:commons-logging:1.1.3")
```

I'll also note: we are using an internal artifactory server to both cache maven central deps (and where we host internal projects). I'm not seeing anything weird with it, so I really am not sure if it's somehow also causing issues.

**Comment by ljacomet** [comment]
Thanks for the report and attempts at reproducing.

These issues are usually caused by corner cases in the dependency graph computation. That's why changing declaration order or adding / removing dependencies can make the problem go away.
Unfortunately, these issues are hard to track without an isolated reproducer.

#14229 fixes such a corner case. Once a nightly with the fix is available, I'll ask you to test it to see if it fixes this issue.

**Comment by ljacomet** [comment]
Can you try with a nightly and let us know how it goes?
https://gradle.org/nightly/

**Comment by tjuricek-vmware** [comment]
No, unfortunately it still had a problem:

```
Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (1345) for constraint platform-runtime -> com.rabbitmq:amqp-client:5.9.0
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:83)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:238)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:130)
        ... 113 more
```

This was using this version:

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 6.7-20200824220048+0000
------------------------------------------------------------

Build time:   2020-08-24 22:00:48 UTC
Revision:     1c64c1d968445857daf8b3d630f22d20b938fce8

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          14.0.2 (Oracle Corporation 14.0.2+12-46)
OS:           Linux 5.4.0-42-generic amd64
```

**Comment by melix** [comment]
Unfortunately we can't figure out what's going on without a reproducer, as it's a particularly difficult thing to debug. We'd appreciate if you can trip down your project/anonymize to a minimal reproducer.

**Comment by tjuricek-vmware** [comment]
Unfortunately, we have a lot of internal dependencies here (with different build approaches, etc), and figuring out a reproduction case wasn't getting anywhere quickly. 

What I may end up doing is learning how to actually build/debug Gradle itself, so I can just locally debug this. But that's not exactly my highest priority, so I can't you when I'd get around to this.

Basically, I think it's probably valid to just say "can't reproduce" and close this issue. If I actually am able to figure out what's going on, I'll re-open it with reproduction details, or reference a new ticket with a reproduction case.

**Comment by shmish111** [comment]
I just had the same problem but with `org.postgresql:postgresql`. I added an explicit `implementation` dependency and that fixed things, very weird

**Comment by ljacomet** [comment]
@shmish111 Any chance that you are using replacement rules?
We are about to fix an issue for Gradle 7.3 rooted in replacement rules that ends up causing this kind of problems.
See #18079

**Comment by shmish111** [comment]
Not that I'm aware of but I will try to remember to try this out once that is released.

**Comment by ljacomet** [comment]
Gradle 7.3 RC1 is out already, could you check with that version?

**Comment by rupebac** [comment]
Having this problem even with 7.3.1

**Comment by shivkumar138** [comment]
`----------
Gradle version: 6.9.2
Plugin version: 3.7.1
 
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':ads-engagement-summary-report-job-azkaban_2.11:compileClasspath'.
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:106)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.access$000(ErrorHandlingConfigurationResolver.java:49)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:215)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.b(SourceFile:113)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.a(SourceFile:66)
        at com.gradle.scan.plugin.internal.b.f.a.h.a(SourceFile:47)
        at com.gradle.scan.plugin.internal.b.f.a.g.a(SourceFile:147)
        at com.gradle.scan.plugin.internal.b.f.c.a(SourceFile:137)
        at com.gradle.scan.plugin.internal.l.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.l.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.l.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.l.l.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.l.c.a(SourceFile:98)
        at com.gradle.scan.plugin.internal.l.g.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.q.a.c(SourceFile:67)
Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /private/var/folders/ft/b5jkwn010tj3llqw2ljgx1h0001dc1/T/gradle6382969199485670936.bin offset 682978 exists? true
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:132)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:189)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:187)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:159)
        at org.gradle.api.internal.artifacts.result.DefaultResolutionResult.getRoot(DefaultResolutionResult.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:213)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.b(SourceFile:113)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.a(SourceFile:66)
        at com.gradle.scan.plugin.internal.b.f.a.h.a(SourceFile:47)
        at com.gradle.scan.plugin.internal.b.f.a.g.a(SourceFile:147)
        at com.gradle.scan.plugin.internal.b.f.c.a(SourceFile:137)
        at com.gradle.scan.plugin.internal.l.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.l.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.l.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.l.l.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.l.c.a(SourceFile:98)
        at com.gradle.scan.plugin.internal.l.g.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.q.a.c(SourceFile:67)
Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (2241) for default -> com.linkedin.container-core:container-ic-impl:1.2.14
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:83)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:239)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:130)
        ... 21 more
`

Cannot do a successful build anymore after this.

**Comment by jacky1234** [comment]
I have the same problem

**Comment by jjohannes** [comment]
Here is a reproducer for the problem in an error case when dynamic versions are involved. 

[**reproducer-14220.zip**](https://github.com/gradle/gradle/files/9820398/reproducer-14220.zip)

In the attached example:
- Run `gradle resolveArtifacts` to get a proper error:
```
Execution failed for task ':resolveArtifacts'.
> Could not resolve all files for configuration ':implementation'.
   > Could not find any version that matches test:module1:11.2.0.+.
     Versions that do not match: 11.1.0.1
     Searched in the following locations:
       - file:/C:/SPU/pwe/tkeasy/default/git-repos/gradle-plugins/reproducer-14220/repo/test/module1/maven-metadata.xml
     Required by:
         project :
```
- Run `gradle dependencies`, or any build with `--scan`, and you get
```
> Could not resolve all dependencies for configuration ':implementation'.
   > Problems reading data from Binary store in .gradle\.tmp\gradle2620150027837008206.bin offset 0 exists? true
...
  Corrupt serialized resolution result. Cannot find selected module (8) for constraint runtimeElements -> test:module1:11.1.0.1
```

This is also a problem if you write tasks that take resolution results with errors as input (using `configuration.getIncoming().getResolutionResult().getRootComponent()` as task input). Instead of getting a proper result to  inspect the error, the build fails.

A workaround to at least keep the build working (with an empty resolution result though) is to use the following as task input:
```
project.provider(() -> {
  try {
    return configuration.getIncoming().getResolutionResult().getRootComponent().get();
  } catch (ResolveException e) {
    project.getLogger().lifecycle("Bug https://github.com/gradle/gradle/issues/14220");
    project.getLogger().lifecycle(e.getCause().getCause().getMessage());
    // empty result
    return project.getConfigurations().detachedConfiguration().getIncoming().getResolutionResult().getRootComponent().get();
  }
});
```

**Comment by jjohannes** [comment]
Another reproducer, this time for a successful resolution:

- clone https://github.com/jjohannes/java-ecosystem-capabilities
- `cd samples/sample-all`
- `gradle dependencies -s` -> build successful
- Do this change in `samples/sample-all/build.gradle.kts` (moves dependency up) - https://github.com/jjohannes/java-ecosystem-capabilities/commit/89f2ba222f8a845ad94d78826eba4a5eea76deb9
- `gradle dependencies -s` -> ERROR ` Corrupt serialized resolution result. Cannot find selected module (101) for compile -> jakarta.activation:jakarta.activation-api:2.1.0`

**Comment by NielsDoucet** [comment]
We had this issue trigger because of the following dependency substitution rule:
```
module("org.hamcrest:hamcrest-core") {
    replacedBy("org.hamcrest:hamcrest", "`hamcrest-core` migrated to `hamcrest`")
}
```

Due to the project's upgrade strategy using shim jars (see https://hamcrest.org/JavaHamcrest/distributables#previous-versions-of-hamcrest), hamcrest-core now depends on hamcrest.
It seems using replacement rules triggers corruption of the serialised dependency graph in this case.

**Comment by jjohannes** [comment]
Follow up to my [previous comment](https://github.com/gradle/gradle/issues/14220#issuecomment-1291618229): After adding even more capability rules and dependencies to the sample in https://github.com/jjohannes/java-ecosystem-capabilities , I can trigger this in more than one way there now (for resolutions that should succeed). Also, in the resolution result, certain entries are missing. Usually, the result should show at least **all direct dependencies** and what they are substituted with.

Reproducer:
- clone https://github.com/jjohannes/java-ecosystem-capabilities
- `cd samples/sample-all`
- `gradle dependencies --scan`
- Inspect dependency report or build scan. Entry for `org.bouncycastle:bcprov-jdk18on:1.71`, and other `org.bouncycastle:bcprov-*` dependencies, are missing. Although they are declared as direct dependency [in the build.gradle.kts](https://github.com/gradlex-org/java-ecosystem-capabilities/blob/36fd98353f17f7860da3c13fa4c8cf086ca6d00f/samples/sample-all/build.gradle.kts#L109-L130)

This is an artificial example that would not exist like this in a real build. Still the result should not be this incomplete and this _might_ be an indication that too much information is discarded during resolution.

This is with Gradle 8.0 RC2

**Comment by kmoens** [comment]
I experienced a similar issue in a multi-module project, with the capabilities of the [Java Ecosystem Capabilities](https://github.com/gradlex-org/java-ecosystem-capabilities) plugin activated together with an extra (own) Hibernate capability.

To reproduce:
- Clone https://github.com/kmoens/gradle-corrupt-serialization-issue-14220
- Run `./gradlew module-a:dependencies`

**Comment by realdadfish** [comment]
For me the problem was that a custom build plugin dependency pulled in an apparently JEE-only library, namely ` jakarta.activation:jakarta.activation-api`. After I removed this specifically from the build plugin via `exclude`, the issue vanished.

**Comment by jvandort** [comment]
It seems there are a number of different issues in this thread (and related threads). There are several ways to get to a corrupt serialized resolution result. This error just means there was _some_ bug in resolution. Furthermore, some of the errors don't produce corrupt results, but instead produce either _missing_ dependencies, fail to detect capability conflicts, or silently fail in other ways. 

I am currently working on [a PR](https://github.com/gradle/gradle/compare/jvandort/dm/document-capability-conflict-reproducers?expand=1) that consolidates all of the reported reproducers into Gradle integration tests -- and making them as minimal as possible. This is the first step to discovering the issue(s) we have to solve. 

@jjohannes Your [first issue](https://github.com/gradle/gradle/issues/14220#issuecomment-1283947029) seems easy to reproduce and seems to have a relatively easy fix. This seems unrelated to the later reproducers.

@jjohannes I've managed to reduce your [second reproducer](https://github.com/gradle/gradle/issues/14220#issuecomment-1291618229) to a minimal reproducer. Minimal reproducers are much more helpful for debugging these issues. This is included in the above-noted PR.

@jjohannes I am having trouble reproducing your [third reproducer](https://github.com/gradle/gradle/issues/14220#issuecomment-1407125074). Would you be able to put together a reproducer showing the missing first-level dependencies in the resolution result? (The bouncycastle one)

@kmoens I tried reproducing your issue, but I cannot resolve your settings script. 
Please provide a standalone reproducer that does not apply a script from a remote URL.

This is indeed a problem that we need to fix. We should not have reliability/correctness issues in the Gradle resolution engine. However, this issue is related to incredibly complicated code in the resolution engine. It may be very difficult to both track down and fix. These bugs in capability conflict resolution were likely present since the introduction of the feature.

**Comment by jjohannes** [comment]
Thank you for looking into this @jvandort. I stripped down the [disappearing dependencies](https://github.com/gradle/gradle/issues/14220#issuecomment-1407125074) reproducer to the following. I think this has something to do with the combination of version upgrades and capabilities. It actually reproduces two (probably related) problems:

- If you keep `implementation("org.bouncycastle:bcprov-jdk14:1.70")` you get the disappearing nodes
(https://scans.gradle.com/s/bevefyii5imiq/dependencies?toggled=W1swXSxbMCwwXV0)
- If you remove that line, you get a capability conflict between two versions of the same (!) module which should not be possible: 
`Cannot select module with conflict on capability 'org.bouncycastle:bcprov-jdk18on:1.72' also provided by [org.bouncycastle:bcprov-jdk18on:1.71(runtime)]`
(https://scans.gradle.com/s/4q6sisa23lbni/dependencies?toggled=W1swXSxbMCwwXV0)

<details>
  <summary>Reproducer build.gradle.kts</summary>

```
plugins {
    id("java-library")
}

dependencies.components {
    listOf("bcprov-jdk14", "bcprov-jdk18on").forEach {
        withModule("org.bouncycastle:$it") { allVariants { withCapabilities { addCapability("foo", "bcprov", id.version) }}}
    }
    listOf("bctls-fips", "bctls-jdk14", "bctls-jdk18on").forEach {
        withModule("org.bouncycastle:$it") { allVariants { withCapabilities { addCapability("foo", "bctls", id.version) }}}
    }
}

configurations.all {
    resolutionStrategy.capabilitiesResolution {
        withCapability("foo:bcprov") { selectHighestVersion() }
        withCapability("foo:bctls") { selectHighestVersion() }
    }
}

dependencies {
    implementation("org.bouncycastle:bcprov-jdk14:1.70") // keep for nodes disappearing / remove for weird conflict error
    implementation("org.bouncycastle:bcprov-jdk18on:1.71")
    implementation("org.bouncycastle:bctls-fips:1.0.9")
    implementation("org.bouncycastle:bctls-jdk14:1.70")
    implementation("org.bouncycastle:bctls-jdk18on:1.72")
}
```
</details>

**Comment by mathjeff** [comment]
Hey thanks for listing a bunch of repros
I think here's another one in case it's interesting: https://github.com/gradle/gradle/issues/26145#issuecomment-1957776331

**Comment by jvandort** [comment]
@mathjeff Yeah I think I’ve got that one in the PR. Ideally we’d be able to simplify this reproducer enough to not need to apply the android plugin.

**Comment by kmoens** [comment]
@jvandort 
The reproducer is back available. I made a wrong commit there which caused it to become unusable, this is now reverted and it is back in the original state: i.e. the reproducer for this issue.

**Comment by jbretsch** [comment]
[gradle-problems-reading-binary-store](https://github.com/jbretsch/bug-reproducers/tree/master/gradle-problems-reading-binary-store) also reproduces the problem. There, the problem disappears by switching the order of the only two dependencies declared in the `build.gradle`.

**Comment by mathjeff** [comment]
Any ideas about things that users might be able to do to help out with this?

**Comment by marcellogalhardo** [comment]
I'm facing an issue while working on converting the AndroidX library `lifecycle-viewmodel-compose` to Kotlin Multiplatform. The problem appears to be related to the library being KMP, with the Android source set depending on livedata-core (Java).

For reference, here are the AOSP changes:
- CLs: [vm-compose-kmp](https://android-review.git.corp.google.com/q/topic:%22vm-compose-kmp%22)
- Reverted CLs: [revert-vm-compose-kmp](https://android-review.git.corp.google.com/q/topic:%22revert-3007635-vm-compose-kmp-ETEPVUDLIN%22)

**Comment by mathjeff** [comment]
We think we found [a workaround](https://issuetracker.google.com/issues/324939349#comment13) in the case of [the previous comment](https://github.com/gradle/gradle/issues/14220#issuecomment-2021021854), which is to explicitly [add a transitive dependency](https://r.android.com/3017197) to the androidMain sourceset from the project encountering the error (`:lifecycle:lifecycle-viewmodel-compose`) to the project providing the artifact that failed to resolve (`:lifecycle:lifecycle-livedata-core`).

Also interesting, if we instead add the transitive dependency to the commonMain sourceset instead, then we get [a resolution ambiguity error](https://ge.androidx.dev/s/i2dfa52ilmrik/failure#1)

**Comment by jvandort** [comment]
Thank you all for your patience on this issue. We have been working hard on these reported problems, many of which are quite complex and trigger edge cases in the resolution engine. 

We have a PR, https://github.com/gradle/gradle/pull/29853, which should resolve a number of the problematic builds reported in this thread. Unfortunately, since the corrupt resolution result error message is a symptom and not a problem itself, this message can appear as a result of different bugs. The linked PR does not solve all the problems reported here. 

We will continue to work through the reproducers submitted here until there are no outstanding issues that cause corrupt graphs. Correctness and stability are a very high priority for Gradle, and we intend to ensure these issues are resolved.

**Comment by jvandort** [comment]
@marcellogalhardo it seems both links you posted require internal google sign-on

@mathjeff Is this the same underlying issue as https://github.com/gradle/gradle/issues/26145#issuecomment-1957776331?

**Comment by mathjeff** [comment]
[I think this is the same](https://github.com/gradle/gradle/issues/14220#issuecomment-1967783567) as https://github.com/gradle/gradle/issues/26145#issuecomment-1957776331, yeah.

Thanks!

**Comment by jvandort** [comment]
Unfortunately the above linked PR has been reverted due to a regression it introduced. The fix will not be included with Gradle 8.10. We will work to include the change in 8.11

**Comment by jvandort** [comment]
We are once again introducing the bugfix in 8.11 with https://github.com/gradle/gradle/pull/30363

**Comment by crogoz** [comment]
I am getting the same error after upgrading to latest gradle version `8.11.1`. Let me know if there is any other details I can provide:
```
Internal error in Develocity Gradle plugin: finished notification
com.gradle.develocity.DevelocityException: Internal error in Develocity Gradle plugin: finished notification
        at com.gradle.develocity.DevelocityException.a(SourceFile:25)
        at com.gradle.scan.plugin.internal.operations.d.a(SourceFile:138)
        at com.gradle.scan.plugin.internal.operations.h.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.q.a.c(SourceFile:67)
        at java.base@17.0.13/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /Users/crogoz/.gradle/.tmp/gradle14438152719818265448.bin offset 5535372 exists? true
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:137)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:184)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:182)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:60)
        at java.base/java.util.Optional.map(Optional.java:260)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.b(SourceFile:115)
        at com.gradle.scan.plugin.internal.c.i.a.e$a.a(SourceFile:72)
        at com.gradle.scan.plugin.internal.c.i.a.e.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.c.i.a.d.a(SourceFile:232)
        at com.gradle.scan.plugin.internal.c.i.c.lambda$attach$2(SourceFile:138)
        at com.gradle.scan.plugin.internal.operations.b$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.operations.b.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.operations.n.a(SourceFile:56)
        at com.gradle.scan.plugin.internal.operations.d.a(SourceFile:136)
        ... 5 more
Caused by: java.lang.RuntimeException: Problems loading the resolution results (0.001 secs). Read 2810 values, last was: 5
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:239)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:135)
        ... 19 more
Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected component (346934) for constraint runtimeElements -> <placeholder_groupName>:<placeholder_name>:<version>
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.ResolutionResultGraphBuilder.visitOutgoingEdges(ResolutionResultGraphBuilder.java:144)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:231)
        ... 20 more


A build scan cannot be produced as an error occurred gathering build data.
Please report this problem via https://gradle.com/help and include the following via copy/paste:

----------
Gradle version: 8.11.1
Plugin version: 3.18
```

**Comment by jvandort** [comment]
@crogoz can you provide a reproducer?

Also what happens if you try the 8.12 nightly? We implemented a fix in 8.12 that resolves this bug in some cases

**Comment by crogoz** [comment]
thanks for the quick reply! I tried now on the nightly version: `gradle-8.12-20241210012659+0000-bin` and I can still see the error. 
I'll try to get a reproducer for you, this is one of the complicated repos with a lot of dependencies.

**Comment by joshfriend** [comment]
This PR fixes the issue for my build: https://github.com/gradle/gradle/pull/31877#issuecomment-2567911153

**Comment by pkubowicz** [comment]
This problem appeared to me in Gradle 8.12.1 today due to json-smart versions disappearing from Maven Central (https://github.com/netplex/json-smart-v2/issues/240).

The stack trace was very similar, just mine mentions 'platform' (I have a subproject with `java-platform`).

```
Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /home/pkubowicz/.gradle/.tmp/gradle5551562548940888109.bin offset 0 exists? true
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:137)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:184)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:182)
Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected component (6877) for constraint platform-runtime -> net.minidev:json-smart:2.5.1
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.ResolutionResultGraphBuilder.visitOutgoingEdges(ResolutionResultGraphBuilder.java:144)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:231)
        ... 135 more
```

Unfortunately, I wasn't able to verify if 8.13 RC fixes the problem, because after Maven Central was fixed, I stopped getting the exception.

**Comment by tresat** [comment]
@jvandort - I fixed this issue, I just attached the wrong PR by mistake.  The proper fix is now attached, this issue can be closed as resolved.

**Comment by mathjeff** [comment]
Thanks!
