### ISSUE TITLE
Eclipse classpath should handle test fixture dependencies properly   

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#14932]
When importing a multiproject gradle build into eclipse that contains test fixture dependencies, these test fixture dependencies are not visible by the dependent project. 

This worked with Gradle 6.6.1 but stopped working with 6.7. It's broken for using the `java-test-fixtures` plugin as well as when declaring `testArtifacts` manually 
 

### Expected Behavior

Declared test artefacts / test fixtures should be available in a dependent project (works with Gradle 6.7)

### Current Behavior

Test fixtures are not seen and project dependencies show `without_test_code`. Out of the box the eclipse plugin should detect usage of the `java-test-fixtures` plugin and provide an opt out for manually created test artifacts.

@donat provided a workaround for now:

```
import org.gradle.plugins.ide.eclipse.model.ProjectDependency
plugins {
    id 'eclipse'
}
eclipse.classpath.file.whenMerged {
    entries.findAll { it instanceof ProjectDependency }.each { it.entryAttributes.remove('without_test_code') }
}
```  

### Context

- started failing with Gradle 6.7

### Steps to Reproduce 

Here's an example project demoing the problem.

[eclipse-test-artifacts.zip](https://github.com/gradle/gradle/files/5414830/eclipse-test-artifacts.zip)

**Comment by jjohannes** [comment]
Fixed in #15198

**Comment by joel-jeremy** [comment]
I can also reproduce this in 7.5.1

**Comment by flozano** [comment]
@jjohannes hi, given that some of us are still reproducing the undesired behaviour described in this issue, would it be possible to reopen the issue?

**Comment by flozano** [comment]
ok, will try to isolate and reproduce, and will open a new one if it makes sense.

thanks!
