### ISSUE TITLE
Race condition causes rare build failure in projects using clean, build, large task file outputs, and org.gradle.parallel

### ISSUE THREAD

**Issue by mmorrisontx** [gradle/gradle#15163]
### Expected Behavior

Builds using large task file outputs and org.gradle.parallel should not fail when running `gradle clean build`.

### Current Behavior

* While the `clean` task is deleting files on one executor, another executor may simultaneously be looking for a new task to run.
* The second executor may find a build task within the same project, and `node.allDependenciesComplete()` ([link](https://code.corp.indeed.com/gradle/gradle/-/blob/0a3517662070e414e2d196d40f5afaddefc32c36/subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java#L552)) will be `true` because build tasks typically do not depend on `clean`.
* The second executor will then call `getResolvedMutationInfo(node)` ([link](https://code.corp.indeed.com/gradle/gradle/-/blob/0a3517662070e414e2d196d40f5afaddefc32c36/subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java#L554)) while the first executor is still deleting files.
* getResolvedMutationInfo internally walks the file tree of the task's output directories. If this happens while those same files are being deleted by the first executor, an exception is thrown:
```
(stack trace taken from gradle 5.6.3, but same issue exists on 6.7)
Could not read path '<snipped>'.
        at org.gradle.api.internal.file.collections.DefaultDirectoryWalker$PathVisitor.visitFileFailed(DefaultDirectoryWalker.java:137)
        at org.gradle.api.internal.file.collections.DefaultDirectoryWalker$PathVisitor.visitFileFailed(DefaultDirectoryWalker.java:66)
        at org.gradle.api.internal.file.collections.DefaultDirectoryWalker.walkDir(DefaultDirectoryWalker.java:60)
        at org.gradle.api.internal.file.collections.DirectoryFileTree.walkDir(DirectoryFileTree.java:160)
        at org.gradle.api.internal.file.collections.DirectoryFileTree.visitFrom(DirectoryFileTree.java:138)
        at org.gradle.api.internal.file.collections.DirectoryFileTree.visit(DirectoryFileTree.java:123)
        at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:119)
        at org.gradle.api.internal.file.AbstractFileTree.getFiles(AbstractFileTree.java:58)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:75)
        at org.gradle.api.internal.file.CompositeFileCollection.iterator(CompositeFileCollection.java:64)
        at org.gradle.execution.plan.DefaultExecutionPlan.canonicalizedPaths(DefaultExecutionPlan.java:729)
        at org.gradle.execution.plan.DefaultExecutionPlan.access$800(DefaultExecutionPlan.java:90)
        at org.gradle.execution.plan.DefaultExecutionPlan$8$1$1.accept(DefaultExecutionPlan.java:622)
        at org.gradle.execution.plan.DefaultExecutionPlan$8$1$1.accept(DefaultExecutionPlan.java:619)
        at org.gradle.api.internal.tasks.properties.FileParameterUtils.resolveCompositeOutputFilePropertySpecs(FileParameterUtils.java:157)
        at org.gradle.api.internal.tasks.properties.FileParameterUtils.resolveOutputFilePropertySpecs(FileParameterUtils.java:114)
        at org.gradle.execution.plan.DefaultExecutionPlan$8$1.run(DefaultExecutionPlan.java:619)
        at org.gradle.execution.plan.DefaultExecutionPlan.withDeadlockHandling(DefaultExecutionPlan.java:679)
        at org.gradle.execution.plan.DefaultExecutionPlan.access$900(DefaultExecutionPlan.java:90)
        at org.gradle.execution.plan.DefaultExecutionPlan$8.visitOutputFileProperty(DefaultExecutionPlan.java:612)
        at org.gradle.api.internal.tasks.properties.annotations.AbstractOutputPropertyAnnotationHandler.visitPropertyValue(AbstractOutputPropertyAnnotationHandler.java:51)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode.visitProperties(AbstractNestedRuntimeBeanNode.java:59)
        at org.gradle.api.internal.tasks.properties.bean.RootRuntimeBeanNode.visitNode(RootRuntimeBeanNode.java:32)
        at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:41)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:42)
        at org.gradle.execution.plan.DefaultExecutionPlan.resolveMutations(DefaultExecutionPlan.java:609)
```

### Context
This issue happens quite frequently on on one of our projects where a task with a large quantity (size and count) of output files runs immediately after a clean task which deletes those same files. Deleting and walking the directory takes several seconds, which greatly increases the chance of the race condition.

### Possible Solution
The DefaultExecutionPlan should probably acquire the project lock before calling into `getResolvedMutationInfo(node)`.

**Comment by attix-zhang** [comment]
Hi @jjohannes , any updates on this one? Would this bug fixed in the near term?

**Comment by jjohannes** [comment]
@attix-zhang right now we are triaging issues to find the critical bugs. The backlog has become messy over the past months unfortunately. Do you (or maybe @mmorrisontx) can verify that this is still an issue with Gradle 7.0? (There was some more work done in the execution engine since 6.7.)

**Comment by mmorrisontx** [comment]
It appears this issue still exists in 7. The affected part of DefaultExecutionPlan appears to have not been impacted by any other v7 changes.

**Comment by ov7a** [comment]
Sorry for the late reply.

This appears to be fixed by
* https://github.com/gradle/gradle/pull/18735
