### ISSUE TITLE
Configuration cache - Task inputs are different in cached and non-cached runs

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#15351]
Using the [this project](https://github.com/gradle/gradle/files/5609087/incremental_kapt.zip)
and running:
`./gradlew :lib:compJava --configuration-cache  --configuration-cache-problems=warn && ./gradlew clean && ./gradlew :lib:compJava --configuration-cache  --configuration-cache-problems=warn`

shows that the task inputs for kapt task are different in the first and in the second run (see logging starting with `KAPT inputs are : ...`)

In the first run there are 5 `output.bin` files (used by incremental KAPT, represent class structure information about classpath entries). In the second run the 2nd `output.bin` has been replaced by `/home/gavra/AndroidStudioProjects/IncrementalKaptStateLoading/lib2/build/classes/kotlin/main`, which was the input to the artifact transform used to produce `output.bin`.

This issue causes https://youtrack.jetbrains.com/issue/KT-43615. This could also be an issue in KAPT Gradle plugin, but there were no warnings generated during state serialization.

Gradle version: `6.8-rc-1`

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/15457

**Comment by gavra0** [comment]
It seems the issue is still there if there are no java sources in the lib2 module.
Using [inckapt.zip](https://github.com/gradle/gradle/files/5666922/inckapt.zip), and running `./gradlew :lib:compJava --configuration-cache --configuration-cache-problems=warn && ./gradlew clean && ./gradlew :lib:compJava --configuration-cache --configuration-cache-problems=warn` reproduces the issue.

**Comment by eskatos** [comment]
Thanks for the report and reproducer @gavra0.
I can confirm this issue is still present in the latest 6.8 nightly `6.8-20201211085410+0000`

**Comment by stephanenicolas** [comment]
I can confirm that when it fails for us, the producer module has no java files, but only kotlin files in `src/main/java`.

**Comment by adammurdoch** [comment]
A fix for the missing Java source files case via https://github.com/gradle/gradle/pull/15537
