### ISSUE TITLE
Fix `Querying the mapped value of provider(interface java.util.Set) before task ':base-services:jar'` in our build

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#16030]
When running a test on the `gradle/gradle` build, you'll get the deprecation message:
```
Querying the mapped value of provider(interface java.util.Set) before task ':base-services:jar' has completed has been deprecated.
```

See this build scan: https://ge.gradle.org/s/4airqqojomgkq/deprecations#26

We need to fix this problem in our build if we want to fail on this behaviour in Gradle 7.0.

**Comment by eskatos** [comment]
Note that this happens only when the configuration cache is enabled and storing the configuration cache
- scan with configuration cache off https://ge.gradle.org/s/iogvgn5agsb5c/deprecations
- scan with configuration cache on, storing https://ge.gradle.org/s/fvpxaqttr5a7g/deprecations
- no scan with configuration cache on, reusing

**Comment by eskatos** [comment]
It seems the remaining offender is now the `ktlint` plugin
https://ge.gradle.org/s/7jyfffomjk43u/deprecations

**Comment by eskatos** [comment]
Fixed by https://github.com/gradle/gradle/issues/16376

**Comment by pvegh** [comment]
Strange, I still get this with Gradle 7.1-rc2 and newest ktlint

**Comment by anuplaldeloitte** [comment]
I am currently running gradle distribution of 7.1 and i am still seeing this issue while running test cases. Attaching screen shot

`<img width="1792" alt="Screenshot 2021-09-22 at 9 53 28 PM" src="https://user-images.githubusercontent.com/70739057/134383519-0dd8f936-76c8-40f1-920c-ff831eb7def1.png">`

**Comment by deviant-studio** [comment]
how can we workaround this?

**Comment by marcin-adamczewski** [comment]
I had a similar error but for `app:processDebugGoogleServices`. I have AGP 7.3.0-alpha07.
Reverting `com.google.gms:google-services` to 4.3.5 helped as a temporary workaround.

**Comment by tieorange** [comment]
Updating gms and **crashlytics** version to 2.9.2 fixed that issue for me:

<img width="1585" alt="image" src="https://user-images.githubusercontent.com/3984517/193845103-04384cc4-7a24-4736-b6a1-367650eb713c.png">
