### ISSUE TITLE
IdentityTransform fails with FileNotFound after updating to 7.5-rc1

### ISSUE THREAD

**Issue by yigit** [gradle/gradle#20778]
AndroidX Github Build started failing after updating Gradle to `7.5-rc-1` from `7.5-20220421031748+0000`

First failure: https://github.com/androidx/androidx/commit/dc4af6559aeea3e9eb285857b06078bb152a56cf

### Expected Behavior
`compileReleaseJavaWithJavac` task should wait for its dependencies.

### Current Behavior
`compileReleaseJavaWithJavac` fails in `IdentityTransform` step with a `FileNotFound` exception. Unfortunately, the file is there after the build so my guess is that it is not waiting for its dependencies properly.

```
 Execution failed for task ':lifecycle:lifecycle-livedata-core:compileReleaseJavaWithJavac'.
2022-05-13T11:22:48.790-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve all files for configuration ':lifecycle:lifecycle-livedata-core:releaseCompileClasspath'.
2022-05-13T11:22:48.790-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Failed to transform lifecycle-common.jar (project :lifecycle:lifecycle-common) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.usage=java-api}.
2022-05-13T11:22:48.790-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > Execution failed for IdentityTransform: /Users/yboyar/src/androidx/out/activity-playground/activity-playground/lifecycle/lifecycle-common/build/libs/lifecycle-common-2.6.0-alpha01.jar.
2022-05-13T11:22:48.790-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          > File/directory does not exist: /Users/yboyar/src/androidx/out/activity-playground/activity-playground/lifecycle/lifecycle-common/build/libs/lifecycle-common-2.6.0-alpha01.jar
```

### Context
Worked in `7.5-20220421031748+0000` (and before), started failing with `7.5-rc-1`.

### Steps to Reproduce 
[checkout AndroidX Github Repo](https://github.com/androidx/androidx)
Might also need the [one time setup instructions](https://github.com/androidx/androidx/blob/androidx-main/CONTRIBUTING.md#one-time-setup)
```
cd <checkout-root>/activity
./gradlew --stop
rm -rf ~/.gradle // important to reproduce
./gradlew buildOnServer --no-build-cache --no-configuration-cache
```

If you re-run `bOS` it will succeed. You can also validate that the missing file is there after the first failure.

### Your Environment
Build scan URL: https://ge.androidx.dev/s/sg2yfkiqoxpti/failure#1

**Comment by yigit** [comment]
also tried 7.5-20220511195339+0000. didn't work.

**Comment by big-guy** [comment]
Thanks @yigit.  We'll try to reproduce this.

Could you give `7.5-20220501001223+0000` a try?

**Comment by yigit** [comment]
I'll try it.
meanwhile, I triggered a bunch of versions on CI.

Looks like `20220427150934` ([build](https://github.com/androidx/androidx/actions/runs/2321426707)) is the last good one and `20220428002320` is the first failure ([build](https://github.com/androidx/androidx/actions/runs/2321461381))

**Comment by yigit** [comment]
@big-guy , triggered a new build for `7.5-20220501001223+0000`: https://github.com/androidx/androidx/actions/runs/2321565000

**Comment by yigit** [comment]
That one failed too with the same error:

https://github.com/androidx/androidx/runs/6429070066?check_suite_focus=true

**Comment by liutikas** [comment]
All the things seem to point to https://github.com/gradle/gradle/commit/0654460d8de07edb1358bfb774c760e47a55cf71

**Comment by DPUkyle** [comment]
I was able to reproduce. Instead of purging the whole Gradle user home (`~/.gradle`), I just did:

`$ rm -rf ../out/activity-playground/activity-playground/lifecycle/lifecycle-common/build/libs` from the `activity` subproject.

This was enough to raise the error. I'll continue investigating.

**Comment by DPUkyle** [comment]
Hi @yigit and @liutikas, sorry for the delay in responding.

We've been looking at the execution graph optimizations which exposed this issue. The reality is the behavior which analyzed the inputs to transformations has been incorrect since at least Gradle 7.4, but something about the androidx setup combined with our recent optimizations has teased out this bug. Unfortunately the proper long-term fix is too disruptive to add to 7.5-rc-2.

Instead I've provided a suggested temporary workaround [here](https://github.com/DPUkyle/androidx/commit/9cd8cce8655b0f1af6773ac42b136e87c45d893b). This should allow you to test with Gradle 7.5-rc-1, and we will make changes in either 7.5.1 or 7.6 which will remove the need for the workaround.

**Comment by DPUkyle** [comment]
> @bamboo I think Adam is looking/working on this. Do you want us to reassign it to him?

This issue is blocked by the root cause, which is being investigated as #20975.

**Comment by adammurdoch** [comment]
This is fixed now via https://github.com/gradle/gradle/pull/21292

**Comment by yigit** [comment]
Unfortunately, we are still seeing this problem with gradle 8:

https://ge.androidx.dev/s/jpkurj73xajqw

**Comment by rolgalan** [comment]
> Unfortunately, we are still seeing this problem with gradle 8:
> 
> https://ge.androidx.dev/s/jpkurj73xajqw

I can confirm we are getting exactly the same problem with `Gradle 8.2` and `Gradle 8.2.1` only if we enable **configuration cache**.

 We detected while executing `sonarqube`, but the error happens during the `kaptGenerateStubsDebugKotlin`. Interestingly enough, if we run first `kaptGenerateStubsDebugKotlin` and then in a separate execution `sonarqube`, **it finishes successfully**.

This happens for us in our CI (on Linux AMIs, with 16 cores) but not locally (on macOS, with 8-10 cores), not sure if the extra available workers or the OS might be connected. This is a project around 140 modules and it always fails in one of the first ones (required by another 14 modules).

**Comment by nuhkoca** [comment]
> > Unfortunately, we are still seeing this problem with gradle 8:
> > https://ge.androidx.dev/s/jpkurj73xajqw
> 
> I can confirm we are getting exactly the same problem with `Gradle 8.2` and `Gradle 8.2.1` only if we enable **configuration cache**.
> 
> We detected while executing `sonarqube`, but the error happens during the `kaptGenerateStubsDebugKotlin`. Interestingly enough, if we run first `kaptGenerateStubsDebugKotlin` and then in a separate execution `sonarqube`, **it finishes successfully**.
> 
> This happens for us in our CI (on Linux AMIs, with 16 cores) but not locally (on macOS, with 8-10 cores), not sure if the extra available workers or the OS might be connected. This is a project around 140 modules and it always fails in one of the first ones (required by another 14 modules).

Hey @rolgalan,

We are facing exactly the same issue. Were you be able to fix this?

**Comment by bamboo** [comment]
Hi @nuhkoca, is that still happening with Gradle 8.9?

**Comment by nuhkoca** [comment]
Hi @bamboo, yes even with `Gradle 8.10`. I am getting this exception

> Execution failed for task ':app:kaptGenerateStubsDebugKotlin'.
> > Error while evaluating property 'friendPathsSet$kotlin_gradle_plugin_common' of task ':app:kaptGenerateStubsDebugKotlin'.
>    > Could not resolve all files for configuration ':app:debugCompileClasspath'.
>       > Failed to transform annotation.jar (project :core:annotation) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=17, org.gradle.libraryelements=jar, org.gradle.usage=java-api, org.jetbrains.kotlin.platform.type=jvm}.
>          > Execution failed for IdentityTransform: /home/runner/work/path/to/project/core/annotation/build/libs/annotation.jar.
>             > File/directory does not exist: /home/runner/work/path/to/project/core/annotation/build/libs/annotation.jar


We have the same scenario as @rolgalan, this exception only occurs in executing `sonarqube` task regardless of configuration cache. We have only one JVM module in our Android project and this started after adding that module, tho.

**Comment by nuhkoca** [comment]
Hey @bamboo, we figured out that this issue is actually originating from Sonar task. Nothing to do with `Gradle`. For now, we converted `JVM` library to `Kotlin` one and issue got resolved. Thanks for helping tho!
