### ISSUE TITLE
Test task avoidance is not working since Gradle 7.4.x

### ISSUE THREAD

**Issue by dreis2211** [gradle/gradle#20846]
Hi,

it seems that the task avoidance for tests is not working anymore since Gradle 7.4.x

### Expected Behavior
Test tasks are not eagerly created

### Current Behavior
Test tasks are eagerly created

### Steps to Reproduce 
Have something like the following in your project
```
tasks.withType(Test).configureEach {
    println "Configure Tests"
    testLogging {
        showStandardStreams = true
        exceptionFormat = 'full'
    }
}
```
`Configure Tests` should not be printed when the test tasks are not run, but it is. For simpler reproduction: https://github.com/dreis2211/gradle-task-avoidance-bug

This seems to be caused by the relatively new `testResultsElementsForTest` infrastructure added in #18834, but I haven't looked too deep yet.

Cheers,
Christoph

**Comment by CristianGM** [comment]
I wasted this morning trying to catch the issue in our codebase...until I found it was Gradle bug.

Just wanted to say, this is quite an issue for us.

**Comment by big-guy** [comment]
This is fixed in 7.6

**Comment by dreis2211** [comment]
@big-guy Do you have a PR/commit where this is fixed?

**Comment by dreis2211** [comment]
This seems not fixed yet in 7.6 snapshot on https://github.com/dreis2211/gradle-task-avoidance-bug,  @big-guy 
```
christoph.dreis@MB-20000266 gradle-task-avoidance-bug % ./gradlew wrapper --gradle-version=7.6-20221012231352+0000
Downloading https://services.gradle.org/distributions-snapshots/gradle-7.6-20221012231352+0000-bin.zip
...........10%............20%...........30%............40%............50%...........60%............70%............80%...........90%............100%

Welcome to Gradle 7.6-20221012231352+0000!

Here are the highlights of this release:
 - Added support for Java 19.
 - Introduced `--rerun` flag for individual task rerun.
 - Added support for incremental compilation following a compilation failure.

Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 32s
1 actionable task: 1 executed

christoph.dreis@MB-20000266 gradle-task-avoidance-bug % ./gradlew build
Configure Tests
```

**Comment by big-guy** [comment]
`./gradlew build` runs tests, so the test task has to be configured.

**Comment by dreis2211** [comment]
@big-guy Well, that was stupid. Sorry for the noise.
Nonetheless, do you have a commit to share where this has been fixed?

**Comment by big-guy** [comment]
It wasn't addressed specifically in a commit, but it's a part of this stream https://github.com/gradle/gradle/pull/21292

The problem was that registered artifacts were eagerly evaluated whenever a project's metadata was built for dependency resolution.  We had some previous attempts at making the artifacts lazy (since most of the time you only want to know that they exist), but this change tackled it more fundamentally by making the process to build the project metadata more on-demand.

**Comment by dreis2211** [comment]
@big-guy Thanks for sharing - highly appreciated. 👍
