### ISSUE TITLE
Ctrl+C kills daemon during run (Java)

### ISSUE THREAD

**Issue by Pluckerpluck** [gradle/gradle#2128]
Just trying to work out if I'm missing something or not. If I am sorry, otherwise this is an issue.

Running 3.5 on Ubuntu 16.10, using Ctrl+C during a build will kill the daemon (specifically during the run task for a Java application, I didn't test otherwise), which is highly annoying when I'm running something such as a web server which doesn't close automatically.

Is this intended? And similarly is there any way to cleanly close the running program when I'm running a Java application? Right now I have the issue of my server not properly shutting down cleanly when I Ctrl+c. Is the only way for me to deal with this to have an alternate shutdown system?

**Comment by rubin55** [comment]
I'm running into this also. I found the following on the old discuss site about this: https://discuss.gradle.org/t/ctrl-c-during-running-build-also-kills-daemon/10158

Nothing seems to have happened with regards to fixing this. 

This affects me as follows: I doe a run (or bootRun when using SpringBoot), gradle starts its daemon, does its prerequisites (test, etc) then "build" comes which in turn "never ends" because bootRun is *supposed* to not end until developer or admin says otherwise (ctrl-c). It is extremely confusing to a new gradle user that a phase (sorry, task) named "build" encapsulates a task called "run"; they should be separate things imho: A build needs to complete; a run runs until exit or interruption!

**Comment by denisk20** [comment]
I'm hitting this issue when running google app engine locally with gradle plugin. Every time I stop the server with CTRL+C I have to wait for 14 seconds for the daemon to start. When I run the same project using maven it starts almost instantly.
The most demotivating thing is that the original issue has been reported 2.5 years ago. There is still no solution however there is a shiny section in gradle docs with animated gifs and stuff where they roast maven and claim that " Gradle (is) at least twice as fast for nearly every scenario". C'mon guys...

**Comment by Pluckerpluck** [comment]
@denisk20 I too think it's absolutely ridiculous that this hasn't been dealt with, especially given the claims of gradles speed.

My current method of avoiding this is simply to run a command such as:

    ./gradlew build && stuffToRun

i.e. a separate out the run instruction, becuase then at least I can develop at some level of speed.

---------------

If gradle isn't going to support cancelling a running program (hell, sometimes the program stays up as a background task for a while before shutting down) then it just shouldn't support run commands at all. At least then we'd know where we stand on things. Because while `run` is built into the java task, it just confuses people.

**Comment by philiparvidsson** [comment]
What's the status here? I'm also running into this problems. It's absolutely unintuitive that ctrl+c kills the daemon but NOT the underlying process.

**Comment by oehme** [comment]
CTRL+C should never kill the daemon, but only cancel the build. If this is not working for you, can you please provide a reproducible example project?

**Comment by denisk20** [comment]
@oehme https://github.com/denisk20/libgdx-dagger2
Run `./gradlew desktop:run` from the root, wait for the window to open, then hit CTRL+C, then re-run the command, notice a `Starting daemon` indicator popping up briefly. Also notice that when you close the window manually (not using CTRL+C) the build starts much faster.

**Comment by philiparvidsson** [comment]
@oehme I experience the same thing as @denisk20

**Comment by oehme** [comment]
This has been fixed by #5249 and you'll be able to try it out once 4.8 RC1 goes out early next week.

**Comment by denisk20** [comment]
@oehme this is fixed for libgdx project that I have posted above, but is still reproducible on an appengine project. I have created a small repo here for you to reproduce quickly: https://github.com/denisk20/appengine-test
Please consider re-opening.

**Comment by oehme** [comment]
@denisk20 The appengine plugin doesn't use `exec` or `javaExec`, but runs the server in a thread directly inside the daemon. This would require a more sophisticated cancellation mechanism, probably with some cooperation from that plugin. Would you mind opening a separate issue for it?

**Comment by denisk20** [comment]
@oehme I have created an issue: https://github.com/gradle/gradle/issues/5468
Still don't quite understand why killing the server which runs inside the daemon kills the daemon itself, probably my mental picture of how the process spawning works here is wrong.

**Comment by oehme** [comment]
@denisk20 The server isn't killed. You are telling Gradle to stop. Gradle cancels the build and waits for 10s. If the build doesn't stop after that the daemon kills itself. The problem are tasks that don't respond to cancellation. We've fixed this for all tasks using `exec`/`javaExec`. But the appengine task is just starting some custom thread which Gradle has no knowledge of or control over.

**Comment by philiparvidsson** [comment]
Running gradle 4.9, this is still not fixed.

How to repro:

1. Run some infinitely running exe with project.exec in any task
2. Run task with gradle
3. Press ctrl+c

Expected:

exe exits and task is cancelled

Actual:

exe keeps running and task is cancelled

Screenshot using webpack-dev-server for nodejs:

![image](https://user-images.githubusercontent.com/1163299/44052824-0ad19daa-9f3e-11e8-9441-1be22c495b5e.png)

As can be seen, the node.exe processes keep running after gradle task is aborted with ctrl+c
(does't matter if I say y or n to prompt)

**Comment by oehme** [comment]
It works as expected. The problem in the program you are using. It doesn't quit when we send the kill signal but instead asks the user for confirmation. This is rather uncommon, command line tools are generally expected to shut down without further confirmation when they receive a kill signal.

**Comment by philiparvidsson** [comment]
@oehme no, it's actually gradlew.bat which asks for it (I just tested it)

**Comment by oehme** [comment]
I guess it's your shell that's asking then. Can you provide a reproducible example project?

**Comment by philiparvidsson** [comment]
file 1: build.gradle

```
task dummy {
  exec {
    commandLine 'python', 'freeze.py'
  }
}
```

file 2: freeze.py

```
import time
while 1:
  print("foo")
  time.sleep(1.0)
````

1. create dir named foo
2. put both files with contents inside it
3. chdir into foo dir
4. type `gradle wrapper`
5. type `gradlew dummy`
6. press ctrl+c

expected results:

python is killed

actual results:

gradle exits, python keeps running

**Comment by oehme** [comment]
You are executing at configuration time. This should be 
```
task dummy(type: Exec) {
  commandLine 'python', 'freeze.py'
}
```

or in case you can't use an Exec task

```
task dummy() {
  doLast {
    exec {
      commandLine 'python', 'freeze.py'
    }
  } 
}

**Comment by oehme** [comment]
So I [changed our integration](https://github.com/gradle/gradle/tree/oehme/exec/verify-shutdown) tests to verify that the program is killed (and not just that Gradle is cancelled) - and indeed it works on Linux, but not on Windows. This could have two reasons:

1. The process is shut down, but the way I'm testing shutdown doesn't work on Windows
2. The process is indeed not shut down. That would mean `Process.destroy()` does not work as desired on Windows. Java 8 introduced a new `destroyForcibly`, which I'm trying out now.

**Comment by philiparvidsson** [comment]
@oehme 

This is what happens when I do it (with your `doLast` fix applied):

![image](https://user-images.githubusercontent.com/1163299/44832751-107d8480-ac2c-11e8-92f8-233f73349dd4.png)

The issue might be that I have python in a .bat-wrapper.

Could you try creating a .bat-file named python.bat with the following content and use that one for the command line in the dummy task:

`@python %*`

**Comment by oehme** [comment]
Can you give the latest 5.0 nightly a try? I did quite a few changes in that area, which might improve the situation.

**Comment by philiparvidsson** [comment]
@oehme I tried 5.0-20180914112317+0000 - same problem! 😢

**Comment by oehme** [comment]
Can you open a new issue with a small sample project, so we can track this independently?

**Comment by philiparvidsson** [comment]
#7603
