### ISSUE TITLE
Typesafe project accessor leak into included build

### ISSUE THREAD

**Issue by martinbonnin** [gradle/gradle#22095]
When using typesafe project accessors and included builds, the included build becomes out-of-date depending if called from the root build or from the included build.

You can reproduce with https://github.com/martinbonnin/test-accessors/tree/076ada8ef52bf171972a6f1da997866c3bbb2d64

```
# Run the included build
./gradlew -p build-logic compileKotlin
# Run the root build, build-logic:compileKotlin will be run again 
./gradlew help -i
[ ... ]
Task ':build-logic:compileKotlin' is not up-to-date because:
  Class path of task ':build-logic:compileKotlin' has changed from 5d5d066a31ec578a38e4c520e519ee10 to a0332dec08439c7ee6085c0ee519aec6.
```

This makes working with included builds cumbersome because they keep doing the same work over and over again.

It looks like this is due to the accessors `.class` file slightly changing between invocations. Can we make sure that the included build always see the same accessors, even when called from the main build?

**Comment by ov7a** [comment]
Sorry for the late reply.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by martinbonnin** [comment]
@ov7a thanks for the reply. It's been a while and I've definitely lost a lot of context on this issue. It might have been fixed already. I have personally stopped using project accessors and am not impacted by this issue. Feel free to close it and I'll reopen if it becomes too much of an issue again.

**Comment by ov7a** [comment]
@martinbonnin, it's most likely still an issue since not much has been done in this area. Unfortunately, we don't have the capacity to work on that area, but we plan to work on it eventually.

**Comment by martinbonnin** [comment]
Sounds good! Thanks for the update 🙏
