### ISSUE TITLE
Version catalog accessors for plugin aliases shown as errors in IDE kotlin script editor

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#22797]
### Expected Behavior

No error should be shown in the IDE kotlin script editor.

### Current Behavior

![issue](https://user-images.githubusercontent.com/132773/202849389-8b79bbfc-0f00-40d9-8ae3-ec1ae74ee0f6.png)

### Workaround

You can install the [Gradle Libs Error Suppressor IntelliJ Plugin](https://plugins.jetbrains.com/plugin/18949-gradle-libs-error-suppressor) or add the `@Suppress("DSL_SCOPE_VIOLATION")` annotation as follows:

![workaround](https://user-images.githubusercontent.com/132773/202849519-9ea31840-400d-4c8f-aa5a-280e3a7e69dd.png)

### Context

This was reported on the Kotlin IntelliJ plugin bug tracker first:

* [KTIJ-19369 - False-positive "can't be called in this context by implicit receiver" with plugins in Gradle version catalogs as a TOML file](https://youtrack.jetbrains.com/issue/KTIJ-19369)

It is in fact a Gradle issue.

Version catalog accessors are available as a `Project` extension, e.g. `libs`, outside of the scope of the `plugins {}` block. This is exactly what the IDE correctly reports.

It works in the Groovy DSL because there the version catalogs are explicitly made available via `ScriptTarget.getPluginsBlockPermits()`. This was not done for the Kotlin DSL.

This was not spotted when adding support for version catalog plugin aliases in the `plugins {}` block because the template class used for the evaluation of the Kotlin DSL plugins block does not restrict access to the `Project` in `CompiledKotlinBuildscriptAndPluginsBlock` (not using the `PluginDependenciesSpecScope` and has `@ImplicitReceiver(Project::class)`). 

This is asymetrical with `CompiledKotlinSettingsPluginManagementBlock` that correctly applies the limitation using `PluginDependenciesSpecScope` which is annotated with `@GradleDsl` but still it has `@ImplicitReceiver(Settings::class)`. This is an old mistake. This should be fixed. IOW version catalogs in the Kotlin DSL plugins block work by accident.

Once fixed it will break usage of version catalog plugin aliases from the `Project` extension in the `plugins {}` block for the Kotlin DSL. In order to make it work again, version catalog accessors should be made available in the `plugins {}` block.

There are of course complications because, although the Groovy DSL applies limitations so that only `<catalogName>.plugins.*` is allowed, there's no such limitation on the Kotlin DSL. The Groovy DSL limitations capture the original intent for the feature but adding the same limitation on the Kotlin DSL to a stable feature is a breaking change. That can only happen on a major Gradle version. It could be introduced behind a feature flag in a minor version though.

### Steps to Reproduce 

* clone https://github.com/eskatos/gradle-kotlin-dsl-version-catalog-plugins-issue
* open in IDE
* open the `build.gradle.kts` file

**Comment by eskatos** [comment]
The issue is in the backlog of the relevant team and prioritized by them.

**Comment by TWiStErRob** [comment]
For SEO (images are not searchable).

The error message is:
> 'val Project.libs: LibrariesForLibs' can't be called in this context by implicit receiver. Use the explicit one if necessary

for this code:
```gradle
plugins {
    alias(libs.plugins.kotlin.jvm)
}
```

Workaround:
```gradle
@Suppress("DSL_SCOPE_VIOLATION")
plugins {
    alias(libs.plugins.kotlin.jvm)
}
```

**Comment by liutikas** [comment]
Any updates here?

**Comment by eskatos** [comment]
@liutikas, this issue is assigned to 8.1 RC1 and associated with a PR already :)

**Comment by eskatos** [comment]
This has been fixed by

* https://github.com/gradle/gradle/pull/23639

This will ship in Gradle 8.1.

You can give it a try starting with `8.1-20230208002420+0000`. You might need to clear IDEA caches and sync your build to see the full effect of the fix.

**Comment by TWiStErRob** [comment]
@eskatos would you mind summarizing the problem's root cause and the fix in 2-3 sentences? I'm really curious how it was working in command line, but not in IDE, yet the fix had to be done in Gradle.

**Comment by Renari** [comment]
It was working in both scenarios, this error did not prevent you from using your project in the IDE, it just made your plugins block show errors which did not prevent budling.

**Comment by eskatos** [comment]
@TWiStErRob please see this issue description and the PR description and commit messages

**Comment by TWiStErRob** [comment]
Thanks Paul, some gold in the commit messages, sorry I didn't notice that.

@Renari in an IDE "red, that otherwise executes just fine" is not considered "working". False positives problem reports really kill confidence in any tool. KTIJ and IDEA projects (YouTrack) are full of false negative / false positives and they treat them as priority bugs most of the time.

**Comment by Renari** [comment]
@TWiStErRob Saying that something isn't working implies that it's dysfunctional, in this scenario. From Gradles perspective everything was functional, while that was a technicality the end result was the same so it was "working", that is producing the desired result despite the raised issue. Usually when someone asks if something is working they're looking for the big picture, you don't tell someone the water plant isn't working because of issues with a single valve.

**Comment by danielesegato** [comment]
@Renari I believe @TWiStErRob is criticizing the priority given to this bug not questioning if it was blocking or not. 

And I've to agree with them.

Having an error reported when there isn't one is not a minor issue. It isn't worst than something breaking, but it is right next in priority. And this one had an huge visibility / impact on users.

I lost half day chasing down this bug to than know it was nothing to worry about and suppressing it, and this was 1 year ago when I migrated to version catalog. You can imagine how much time people lost with this in the last year. And it surely hurt really hard the adoption of that feature. It also scare away early adopters for trying new features when they come.

That said, thanks for fixing it. I just hope you'll have an internal discussion on how you chose priority bugs.

**Comment by lukasz-kalnik-gcx** [comment]
Let's just step back and appreciate that we are able to make a living off of a **free** build system which Gradle provides to us.
Unless you are a paying Gradle customer.

**Comment by Vampire** [comment]
I think it also was not clear from the beginning that this had to be fixed in Gradle. As it is building fine, assumption probably was, and imho rightfully, that the needs to be fixed in IntelliJ. Until JetBrains investigated the issue and told, that it needs a fix inside Gradle.

**Comment by TWiStErRob** [comment]
Yeah, I followed it through the lifecycle as @Vampire said, there were a 2 or 3 issues with Version Catalogs, and some of them were actually fixed by JetBrains, this wasn't really clear where it fits. I wasn't criticizing the priority in Gradle, in the end they fixed in in 3 months after realizing it belongs here (and that includes the holiday season, so 👏).

I was trying to explain my view that "red" in IDE is synonymous to breaking, because it's stops us from doing our job, while trying to understand an error that doesn't exists. Luckily only temporarily. One of the IDE's job is to show the problems that exists in our code at the right place at the right time (hence "integrated"). There was no issue in our code here, as it's clear from the OP: Gradle actually allowed more than it should have, but IDEA was flagging it as "wrong".

This has all kinds of psychological effects, and I definitely agree it hurt the adoption of Version Catalogs. Build systems in general don't have a good reputation, few quotes from yesterday from a colleague: "_Sick and tired of gradle_", "_What is the hell??? How come???_", "_Why is it so unstable and unpredictable? Can't Gradle handle such a simple task?_"; not related to this issue in particular, but this just emphasizes that adding false positives on top of the already complex build system is just going to hurt more.

@eskatos thank you very much for the fix again! Could you please make sure to put a section in the 8.1 upgrade guide to let people know that they can remove ["the suppression"](https://github.com/search?q=DSL_SCOPE_VIOLATION+filename%3Abuild.gradle.kts&type=Code) once their wrapper is set to 8.1+?

**Comment by eskatos** [comment]
@TWiStErRob, good point

Please take a look
* https://github.com/gradle/gradle/pull/23832

**Comment by danielesegato** [comment]
Yes, I'm sorry my comment come out harsher than I intended. I appreciate Gradle and that this was fixed.

**Comment by DavidGregory084** [comment]
@eskatos I'm still experiencing errors like this when using the Tooling API even with version `8.1-20230208002420+0000`. Is that a separate issue or should it be fixed at that version? Does the consumer Gradle version need to be updated as well?

I have a reproducer [here](https://github.com/opencastsoftware/gradle-bsp). The error can be replicated via `./gradlew :server:run`.

```java
        ProjectConnection gradleConnection = GradleConnector.newConnector()
            .forProjectDirectory(Paths.get(".").toFile())
            .useGradleVersion("8.1-20230208002420+0000")
            .connect();

        BasicGradleProject projectModel = gradleConnection.getModel(BasicGradleProject.class);
```
===>
```
org.gradle.tooling.BuildException: Could not fetch model of type 'BasicGradleProject' using connection to Gradle distribution 'https://services.gradle.org/distributions-snapshots/gradle-8.1-20230208002420+0000-bin.zip'.
```

```
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file '/Users/davidgregory/Repos/gradle-bsp/server/build.gradle.kts' line: 25
Script compilation errors:

  Line 25:     implementation(libs.gradleToolingApi)
                              ^ Unresolved reference: libs

  Line 27:     implementation(libs.bsp4j)
                              ^ Unresolved reference: libs

  Line 29:     implementation(libs.picocli)
                              ^ Unresolved reference: libs

  Line 30:     annotationProcessor(libs.picocliCodegen)
                                   ^ Unresolved reference: libs

  Line 32:     runtimeOnly(libs.logback)
                           ^ Unresolved reference: libs
```
The full stacktrace is [here](https://gist.github.com/DavidGregory084/cc78cb6af1c12c5efcb763f4459ee130).

**Comment by eskatos** [comment]
Hi @DavidGregory084,

This issue is unrelated to the problem you are experiencing.
Thank you for opening https://github.com/gradle/gradle/issues/24046

**Comment by Shayne3000** [comment]
Just adding in case someone comes across an `expression expected error` after implementing this fix. Change suppress annotation to `@file:Suppress("DSL_SCOPE_VIOLATION")` instead of `@Suppress("DSL_SCOPE_VIOLATION")`

**Comment by Vampire** [comment]
@Shayne3000 just update your Gradle version and remove the suppression, it is fixed now. ;-)

**Comment by ErfanSn** [comment]
> @Shayne3000 just update your Gradle version and remove the suppression, it is fixed now. ;-)

Not for me with latest version

**Comment by Vampire** [comment]
Did you refresh the Gradle project?

**Comment by ErfanSn** [comment]
Yes, I actually use it in android studio

**Comment by ErfanSn** [comment]
> Did you refresh the Gradle project?

Of course, the problem is not for alias, but the same problem still exists.

![2023-08-04 (1)](https://github.com/gradle/gradle/assets/50053121/1b63ca87-b4b0-4474-a767-db434c398bfb)

**Comment by TWiStErRob** [comment]
If that's valid Gradle, it's probably worth a separate issue.

**Comment by Vampire** [comment]
You said you updated AGP to 8.1.1, but that is pretty irrelevant.
The important question is, did you update Gradle to 8.1+ in which this issue is fixed?

**Comment by sedubois** [comment]
Thank you, indeed I mixed them up. After upgrading to Gradle 8.3 the errors are gone 👍 (Android Studio : File > Project Structure > Project > Gradle Version)

**Comment by henrik242** [comment]
@Monabr You should use the latest Gradle release version (**8.6**) when testing

**Comment by Vampire** [comment]
That has nothing to do with this issue though.
This was about a similar error you got when legally using the `libs.plugins...` in the `plugins { ... }` block.
You get it because you illegally use `rootProject` within the `plugins { ... }` block.
Use a version catalog instead of extra properties which are practically always just a hack for doing something not properly and you are fine.
