### ISSUE TITLE
Gradle 8 reports incorrect Configuration flags despite being configured correctly

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#24197]
As part of the [Nokee project](https://nokee.dev), we encountered the following erroneous reporting from Gradle information log.

### Expected Behavior

There shouldn't be any information logs printed out for each consumable `Configuration`.

### Current Behavior

Gradle reports the following for each consumable `Configuration` part of a dependency resolution:
```
The configuration :fooElements is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
```

### Context

The reports come from [`DefaultConfiguration#logIfImproperConfiguration`](https://github.com/gradle/gradle/blob/5c9b8ef4c2d2ff0760e5d12dc8aa409e0e692fa4/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L1743). However, it seems by default `canBeDeclaredAgainst` comes from this new, half-implemented feature,  `ConfigurationRole`. There is no mention in the release notes of any changes with regard to role-at-creation for `Configuration`. It's possible to change the `canBeDeclaredAgainst` flag, but only via an internal setter [`DeprecatableConfiguration#setCanBeDeclaredAgainst`](https://github.com/gradle/gradle/blob/5c9b8ef4c2d2ff0760e5d12dc8aa409e0e692fa4/subprojects/core-api/src/main/java/org/gradle/internal/deprecation/DeprecatableConfiguration.java#L125). In fact, that method is marked as 8.1 which seems to have leaked into Gradle 8.

### Steps to Reproduce 

Suppose the following code:
```
configurations.create('fooElements') {
  canBeConsumed = true
  canBeResolved = false
  attributes {
    attribute(Attribute.of("my.attribute", String), "value")
  }
}

configurations.create('foo') {
  canBeConsumed = false
  canBeResolved = true
  attributes {
    attribute(Attribute.of("my.attribute", String), "value")
  }
}

dependencies {
  foo project
}

tasks.register('sayHello') {
  doLast {
    println 'Hello, world!'
    configurations.foo.resolve()
  }
}
```

Executing `./gradlew sayHello -i` will report incorrect `Configuration` flags.

### Your Environment

Build scan URL:

**Comment by tresat** [comment]
Thank you for reporting this.  I've confirmed the reproducer, and it is a bug.

This should not be happening for any configurations created outside of those created by Gradle core plugins.  We don't want to clutter even the info-level log with these reports just yet, since, like you've said, there's nothing you can do about it currently via the public APIs.  It's meant to help internal development work.  We'll fix this.

> this new, half-implemented feature, ConfigurationRole. There is no mention in the release notes of any changes with regard to role-at-creation for Configuration.

This is part of work that will span several Gradle releases, which we are attempting to do slowly to maintain backwards compatibility and not impact users just yet.  "Half-implemented" is generous at this point, it's step 1, and not meant for public use. 😄 

> In fact, that method is marked as 8.1 which seems to have leaked into Gradle 8.

This `@since` tag is also a mistake that we'll correct.  The scope of what we want to accomplish with this work in each release has changed many times, and updating this was missed.

**Comment by lacasseio** [comment]
There was no mean disrespect with the "half-implemented" comment; it was more a means to illustrate the missing public part of the feature. Is there a design doc that we can read about this work? I'm a bit fearful with the impact on Nokee.

**Comment by tresat** [comment]
Sure, here's the original plan: https://docs.google.com/document/d/1a2vtM10FiWdTpnY8b2S-q28Cl0xUEVIzAOl3BpOeyng/edit#heading=h.jqujzlhqhoob
And the more recent plan for what is/will be done in 8.1: https://docs.google.com/document/d/1vBWyHSaUYHUlh8Xs7lWC1asGv4z8ww0F_qAjhKBC8h8/edit#heading=h.iaxntumehbo4
And the (still to be finalized) plan for 8.2: https://docs.google.com/document/d/1WDzxOnkBn82VhhtmxU3U3TfdyKqkMcBpBFiioJdopPk/edit#heading=h.8cpx7cw8oiiq

Making this API public seems unlikely in 8.2 at this point.

**Comment by lacasseio** [comment]
Thanks for the links to the document. I added a couple of comments, but [one comment, in particular, raises a great question on how we can simplify the implementation](https://docs.google.com/document/d/1a2vtM10FiWdTpnY8b2S-q28Cl0xUEVIzAOl3BpOeyng/edit?pli=1&disco=AAAAsiOEGhA). It would be great to have your input on that.

It's great to see this moving forward; I'm just really concerned about using the factory method to specify and lock the intent (see comment above).

**Comment by MartinHaeusler** [comment]
Just wanted to say that I'm seeing the reported behavior also in Gradle 8.1. Is that to be expected? Or should it be fixed in 8.1 already?

**Comment by tresat** [comment]
@MartinHaeusler can you please provide a reproducer?

**Comment by Omico** [comment]
> @MartinHaeusler can you please provide a reproducer?

Still reproduce in Gradle 8.1.1. Please take a look at https://github.com/Omico/Elucidator.

```
The configuration detachedConfiguration1 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration1 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration detachedConfiguration1 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration1 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :elucidator-generator:classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :elucidator-generator:classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :elucidator-generator:classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :elucidator-generator:classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :elucidator-generator:classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :elucidator-generator:classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
```

**Comment by tresat** [comment]
An update on this: `canBeDeclaredAgainst` will be queryable and settable in the public `Configuration` API in the upcoming Gradle 8.2.

To avoid seeing these messages in the log, you should update your configurations using these methods to avoid having incorrect multiple roles as indicated upon upgrading to Gradle 8.2.  The message will continue to print for non-legacy configurations, and will likely be expanded to apply to legacy configurations at some point prior to Gradle 9.0.

Our perspective is that this is a message which isn't (yet) a deprecation warning that would fail your build, but gives you a helpful heads up that something isn't idiomatic.  Further work is progressing to move configurations to being only single role, so these situations will have to be addressed at some point (possibly Gradle 9.0) and doing so earlier will be less painful.

**Comment by MykolaArlo** [comment]
Observing the same messages even with 8.2.1 builds:
```
11:46:45  The configuration :hmsam:detachedConfiguration246 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration246 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  The configuration :hmsam:detachedConfiguration246 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration246 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  The configuration :hmsam:detachedConfiguration246 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration246 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  The configuration :hmsam:detachedConfiguration247 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration247 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  The configuration :hmsam:detachedConfiguration247 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration247 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  The configuration :hmsam:detachedConfiguration247 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration247 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  Excluding []
11:46:45  The configuration :hmsam:detachedConfiguration248 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration248 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  The configuration :hmsam:detachedConfiguration248 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration248 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  The configuration :hmsam:detachedConfiguration248 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration248 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  The configuration :hmsam:detachedConfiguration248 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration248 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  The configuration :hmsam:detachedConfiguration248 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration248 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  The configuration :hmsam:detachedConfiguration249 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration249 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  The configuration :hmsam:detachedConfiguration249 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration249 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
11:46:45  The configuration :hmsam:detachedConfiguration249 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
11:46:45  The configuration :hmsam:detachedConfiguration249 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
```

**Comment by paco-sparta** [comment]
@tresat Most of the reporters here are not doing anything particularly interesting in our gradle configs. We use plugins from 3rd parties and these messages come from them. None of what you said in your message made sense to me or maps to our gradle files.

What we're asking is that you meet your users where we are, and this migration isn't and it's clogging our CI logs.

**Comment by tresat** [comment]
@paco-sparta - This message is intended to give you a heads up that something is incorrect in the state of your project.  It makes no distinctions whether that problem lies in your build script, or in the logic of the plugins you apply, or some combination of these.

We've enabled this warning because Gradle's configuration API will be changing, and we want to give build authors time to figure out how to correct this improper multiple usage.  Addressing this now will help you migrate and will likely be a prerequisite for upgrading to an upcoming major version of Gradle.

We understand you have no control over 3rd party plugins and we are talking with JetBrains and other major 3rd party plugin providers about how to make sure their plugins behave idiomatically correctly.  Unfortunately we can't anticipate or test every combination of plugins and build setups, so there may be some temporary un-actionable warnings in logs while the ecosystem adjusts.

**Comment by paco-sparta** [comment]
You could make the logs less verbose. Plugin makers will see it and repro it once, we don't need every CI job in the industry to have an additional 10k lines per task.

**Comment by rburgst** [comment]
is there a way to figure out which plugin is adding those configurations so that we can create issues on their github? Right now I dont even know who to blame.

**Comment by rdehuyss** [comment]
Hi, I'm Ronald - the creator of [JobRunr](https://github.com/jobrunr/jobrunr), an open-source distributed scheduler. I want to voice my concern also around this. I just updated to Gradle 8.2.1 to try to solve this issue that I have since Gradle 8.1.1. The log statements are still there...


```
The configuration detachedConfiguration1 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration detachedConfiguration1 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
```

If you want a reproducible scenario, please see my `build.gradle` files in the JobRunr repo.

**Comment by ericparton** [comment]
I'm also still seeing these log messages everywhere, even on Gradle 8.3

**Comment by ujhazib** [comment]
We don't even create any kind of configurations ourselves and gradle 8.3 reports the above two lines from @rdehuyss for (I think ALL) configurations which a build encounters.

**Comment by big-guy** [comment]
FYI, these messages were removed in 8.4.

**Comment by artemptushkin** [comment]
Finally, good news ☝️ all the user's concerns are so valuable, and summarised by Paco above. I really do not understand how the maintainers were trying to explain to us anything, it's relevant only to the plugin developers and the Gradle team itself probably. But we got our logs populated for several months.
