### ISSUE TITLE
Filesystem watching breaks with symlinks

### ISSUE THREAD

**Issue by equeim** [gradle/gradle#27940]
### Current Behavior

In my project I have an included build (Gradle plugin) that has a `/gradle` directory as a symbolic link to root project's parent directory (to reuse wrapper and version catalog without copying them since it's in the same Git repo).
This results in the following warning when running Gradle:
```
Caught exception: Already watching path: /home/alexey/projects/tremotesf-android/gradle-plugin/gradle
Stopping file watching and invalidating VFS after an error happened
```

Here is how project's structure looks:
```
├── app
├── bencode
├── build
├── build.gradle.kts
├── CHANGELOG.md
├── common
├── fastlane
├── gradle
│   ├── libs.versions.toml
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradle-plugin
│   ├── build.gradle.kts
│   ├── gradle -> ../gradle
│   ├── gradle.properties -> ../gradle.properties
│   ├── gradlew -> ../gradlew
│   ├── gradlew.bat -> ../gradlew.bat
│   ├── settings.gradle.kts
│   └── src
├── gradle.properties
├── gradlew
├── gradlew.bat
├── LICENSES
├── local.properties
├── README.md
├── rpc
├── settings.gradle.kts
└── torrentfile
```

### Expected Behavior

No errors, filesystem watching works.

### Steps to Reproduce

1. Clone https://github.com/equeim/tremotesf-android
2. Run Gradle

This error does not appear 100% of the time, but very often.
Also, it seems that it tied to configuration cache somehow? I don't see this error when running Gradle with `--no-configuration-cache`.

### Gradle version

8.6

### Your Environment (optional)

OS: Linux, Fedora 39

**Comment by lptr** [comment]
This should be fixed in 8.7 (RC1 expected on Monday). Could you try reproducing the problem with a nightly version of Gradle? https://gradle.org/release-nightly/

**Comment by equeim** [comment]
> This should be fixed in 8.7 (RC1 expected on Monday). Could you try reproducing the problem with a nightly version of Gradle? https://gradle.org/release-nightly/

Nope, still getting an error (with both nightly and RC1 that was released just now):
```
Caught exception: Already watching path: /home/alexey/projects/tremotesf-android/gradle-plugin/gradle
Unable to watch the file system for changes. Unable to watch same file twice via different paths: Already watching path: /home/alexey/projects/tremotesf-android/gradle-plugin/gradle.
```

**Comment by mboos** [comment]
I'm observing this failure still with 8.7 RC4. In our case, I have the `gradle` folder symlinked from at least two different locations in my repo.

**Comment by mboos** [comment]
If it helps, I do not see this error on MacOS 14.3 with the same repo, just Linux.

**Comment by lptr** [comment]
> If it helps, I do not see this error on MacOS 14.3 with the same repo, just Linux.

Thanks, this is useful indeed.

**Comment by kalayda** [comment]
Confirm the problem.  
Gradle 8.7 on Windows 11.  
The same problem with includeBuild("\\unc\path").

**Comment by viluon** [comment]
Just ran into this with Gradle 8.11 on Ubuntu 22.04.5.

**Comment by dgerhardt** [comment]
I can confirm that Gradle 9.2.1 is still affected by this issue. Tested on Ubuntu 24.04.

**Comment by joshfriend** [comment]
I also just ran into this on 8.14.3. Our developers all use macs and we have never seen this issue there. Our CI is linux but we aren't reusing daemons so I never noticed this until testing non-ephemeral remote dev environments

**Comment by martinbonnin** [comment]
Still there with Gradle 9.4.0 and Debian 12, same linux CI use case
