### ISSUE TITLE
DefaultFileSystemAccess.snapshot sometimes ignoring filter

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#29205]
### Current Behavior

I’m finding that in certain circumstances, the filter assigned to a FileCollection is ignored.

In DefaultFileSystemAccess.snapshot there is an early exit [here](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L163) to check for existing FileSystemLocationSnapshots, and if one is found, then the snapshot is used, regardless of whether a [filter was passed](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L155) to the `snapshot()` function

Normally this case doesn’t trigger, because there are other early exits in `readSnapshotFromLocation()` such as [here](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L197) which do [apply the filter](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L198), and [there is a lock](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L196) in `readSnapshotFromLocation()` to try to prevent computing multiple snapshots of the same directory at a time (see [comment](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L195)).

However, if DefaultFileSystemAccess simultaneously tries to load information about a parent and child directory at the same time, then it is possible that [updates](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java#L181) of the parent directory in the [virtual file system](https://github.com/gradle/gradle/blob/v8.7.0/platforms/core-execution/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java) will also cause corresponding updates of the child directory, even while DefaultFileSystemAccess holds a lock on the child directory. These concurrent updates can then trigger the ignoring of a `FileCollection`'s filter.

### Expected Behavior

It would be nice if the filter assigned to a `FileCollection` weren't ignored

### Context (optional)

In AndroidX we've been observing our `compileKotlin` tasks to be intermittently out-of-date: https://issuetracker.google.com/issues/321949384 and this seems to be the cause

### Steps to Reproduce

I've uploaded a repro case to https://github.com/mathjeff/gradle-samples-2/tree/main/snapshot-wrong

Because reproducing this issue involves a race condition, I've also uploaded a test Gradle change that exacerbates the race condition by adding an additional hard coded sleep for a specific path (the child path) at https://github.com/gradle/gradle/compare/master...mathjeff:gradle:test-exacerbate-snapshot-race-condition

The test.sh script in the repro case takes care of applying this change before running the test

### Gradle version

8.7.0

**Comment by lptr** [comment]
Thanks again for the detailed investigation, and the reproducer! It should be fixed in 8.9 via https://github.com/gradle/gradle/pull/29575.

**Comment by mathjeff** [comment]
Thanks!

**Comment by liutikas** [comment]
It seems that this is not fully fixed as we see nearly an identical issue trying to upgrade to Kotlin Gradle Plugin 2.0.0 when using gradle-8.9-20240618012348+0000-bin.zip release nightly that contains #29575

https://issuetracker.google.com/issues/348019365

**Comment by liutikas** [comment]
Scans from the reproduction.

[First build](https://ge.androidx.dev/s/r7625wgl5xpwq/timeline?details=t7wsb75vod3g4&name=:compose:material:material:compileTestKotlinDesktop)

[Second build](https://ge.androidx.dev/s/y3qj7wahqo3ig/timeline?details=t7wsb75vod3g4&name=:compose:material:material:compileTestKotlinDesktop)

**Comment by liutikas** [comment]
Turns out my issue is a separate bug, this time in KGP code https://youtrack.jetbrains.com/issue/KT-69330/KotlinCompile-friendPathsSet-property-is-racy-due-causing-build-cache-invalidation

**Comment by ljacomet** [comment]
Thanks Aurimas for closing the loop, keeping this issue closed as fixed then.
