### ISSUE TITLE
Gradle picks the wrong daemon Java toolchain

### ISSUE THREAD

**Issue by sschuberth** [gradle/gradle#30652]
### Current Behavior

Gradle picks a Linux system's JRE (i.e. not JDK, with `javac`) as the Java toolchain for the daemon although a JDK is property detected by `./gradlew javaToolchains`.

### Expected Behavior

The daemon JVM should be pick the same Java toolchain as the standard mechanism does (when configured with the same constraints, i.e. a major version only).

### Context (optional)

Context from [Slack](https://gradle-community.slack.com/archives/CAHSN3LDN/p1726725427893599):

I have a weird case where running `./gradlew javaToolchains` includes

```
 + Eclipse Temurin JDK 21.0.4+7-LTS
     | Location:           /home/sebastian/.gradle/jdks/eclipse_adoptium-21-amd64-linux.2
     | Language Version:   21
     | Vendor:             Eclipse Temurin
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Current JVM
```

but if I add `gradle/gradle-daemon-jvm.properties` with

```
toolchainVersion = 21
```

I start getting

```
* What went wrong:
A problem occurred configuring project ':buildSrc'.
> Failed to calculate the value of task ':buildSrc:compileJava' property 'javaCompiler'.
   > Toolchain installation '/usr/lib/jvm/java-21-openjdk-21.0.4.0.7-2.fc40.x86_64' does not provide the required capabilities: [JAVA_COMPILER]
```

Note that on Fedora, despite the path being called "java-21-open*jdk*-...", this actually is a JRE without `javac` [by design](https://discussion.fedoraproject.org/t/javac-not-found/77520).

### Self-contained Reproducer Project

https://github.com/sschuberth/gradle-issue-30652-reproducer

### Gradle version

8.10.1

### Your Environment (optional)

Fedora Linux 40

**Comment by sschuberth** [comment]
I cannot make CI in the reproducer to fail, but locally I can reproduce the issue with that repository.

**Comment by sschuberth** [comment]
This is just to confirm that the issue persists with Gradle 8.11.1 on Fedora 41:

- Ensure that the Gradle daemon is stopped (`./gradlew --stop`).
- Do *not* set the `org.gradle.java.home` property or the `JAVA_HOME` environment variable.
- Ensure that `./gradlew javaToolchains` contains a matching Java 21 JDK.

In my case I have

```
 + Eclipse Temurin JDK 21.0.4+7-LTS
     | Location:           /home/sebastian/.gradle/jdks/eclipse_adoptium-21-amd64-linux.2
     | Language Version:   21
     | Vendor:             Eclipse Temurin
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Auto-provisioned by Gradle

 + Red Hat, Inc. JRE 21.0.5+11
     | Location:           /usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc41.x86_64
     | Language Version:   21
     | Vendor:             Red Hat, Inc.
     | Architecture:       amd64
     | Is JDK:             false
     | Detected by:        Common Linux Locations
```

but `./gradlew classes` fails with

```
* What went wrong:
Could not resolve all dependencies for configuration ':buildSrc:buildScriptClasspath'.
> Could not resolve project :buildSrc.
  Required by:
      project :buildSrc
   > Failed to calculate the value of task ':buildSrc:compileJava' property 'javaCompiler'.
      > Toolchain installation '/usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc41.x86_64' does not provide the required capabilities: [JAVA_COMPILER]
```

as the daemon seems to pick the system's Java 21 toolchain that has `Is JDK: false` instead of picking the Temurin one that has `Is JDK: true`.

Changing `gradle/gradle-daemon-jvm.properties` from

```
toolchainVersion = 21
```

to

```
toolchainVersion = 21
toolchainVendor = Adoptium
```

works around the issue.

**Comment by sschuberth** [comment]
A probably similar error occurs when using the `windows-2022` GitHub runner: Although the docs state that [Java 21 is installed](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#java), [the daemon Java toolchain detection seems to be unable to find it](https://github.com/oss-review-toolkit/ort/actions/runs/12221743341/job/34091181567?pr=9563#step:4:34). Again, this issue seems to be specific to the daemon Java toolchain detection; "regular" Java toolchain detection for the build seems to work.

**Comment by sschuberth** [comment]
I've updated the [reproducer](https://github.com/sschuberth/gradle-issue-30652-reproducer) to show that while [there is a JDK 21 installed](https://github.com/sschuberth/gradle-issue-30652-reproducer/actions/runs/12221993494/job/34091726320#step:2:5) on Windows, [the daemon Java toolchain detect does not find it](https://github.com/sschuberth/gradle-issue-30652-reproducer/actions/runs/12221993494/job/34091726320#step:5:24).

**Comment by Deishelon** [comment]
I've noticed the same issue too

**Comment by sschuberth** [comment]
I was reading the in the [IntelliJ IDEA 2025.1 EAP release notes](https://blog.jetbrains.com/idea/2025/01/intellij-idea-2025-1-eap/#support-for-gradle-daemon-toolchains) that "with Gradle 8.13, you can define the exact JVM for the Gradle Daemon [using the native Gradle toolchain](https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:daemon_jvm_criteria)". So maybe that's a good chance to look at this issue for the Gradle 8.13 milestone, too, @donat?

**Comment by marcphilipp** [comment]
I opened https://youtrack.jetbrains.com/issue/IDEA-366161 for a similar issue where the "JDK" shipped with IntelliJ IDEA gets picked. Why does Gradle consider it a JDK if it doesn't contain the `jar` tool?

**Comment by Vampire** [comment]
It does not, it is considered a Java Toolchain which is correct, if you only need `java` for example for a `JavaExec` task that is fine.
But if you need the `javac` tool for example for a `JavaCompile` task, at that point it complains that no compiler is found.
If you for example have a toolchain set in your build it would be fine if Gradle is executed with a JRE as the configured toolchain would then be used for `JavaCompile`.
But if you did not configure a toolchain in your build, the one used to execute Gradle is used and then it complains that no compiler is found when it needs on.

**Comment by Vampire** [comment]
@sschuberth sorry if I was unclear, that was just referring to Marc's comment.

The Toolchain precedence rules have as second-most significant criterion that a JDK is preferred over a JRE,
so if a JRE and a JDK is found and the JDK can fulfill the version / vendor requirement indeed the JDK should be used imho also for the daemon toolchain.

**Comment by ljacomet** [comment]
This should be fixed in Gradle 8.13, where for the Daemon JVM Gradle will request a full JDK, including one that has the `jar` tool, see #32146

**Comment by fthevenet** [comment]
I've ran into the same issue but what I don't understand is that even after I upgraded the system java on Fedora 41 to a full JDK (i.e. ` dnf install java-21-openjdk-devel`), my build still fails with the same error:
```
* What went wrong:
Execution failed for task ':binjr-core:compileJava'.
> Error while evaluating property 'javaCompiler' of task ':binjr-core:compileJava'.
   > Failed to calculate the value of task ':binjr-core:compileJava' property 'javaCompiler'.
      > Toolchain installation '/usr/lib/jvm/java-21-openjdk-21.0.6.0.7-1.fc41.x86_64' does not provide the required capabilities: [JAVA_COMPILER]
```
Indeed, `gradle  javaToolchains`  does not consider it a JDK:
```
+ Red Hat, Inc. JRE 21.0.6+7
     | Location:           /usr/lib/jvm/java-21-openjdk-21.0.6.0.7-1.fc41.x86_64
     | Language Version:   21
     | Vendor:             Red Hat, Inc.
     | Architecture:       amd64
     | Is JDK:             false
     | Detected by:        Current JVM
```

Yet, there is a reachable `javac` at this location:
```
$ sudo update-alternatives --config javac

There is 1 program that provides 'javac'.

  Selection    Command
-----------------------------------------------
*+ 1           java-21-openjdk.x86_64 (/usr/lib/jvm/java-21-openjdk-21.0.6.0.7-1.fc41.x86_64/bin/javac)

```

If I install a JDK 23 using `dnf install java-latest-openjdk-devel` and select this toolchain with ` update-alternatives`, then everything works as expected.

Am I doing this wrong or is this the same bug? A different one?

Thanks!

**Comment by ljacomet** [comment]
Resolved in #32253
