### ISSUE TITLE
Using Java 24+ toolchain emits warning due to restricted method in java.lang.System being called

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#31625]
### Current Behavior

When running a `JavaCompile` or `Checkstyle` task with JDK 24-ea or 25-ea, the following warning is emitted to stderr:

```
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by net.rubygrapefruit.platform.internal.NativeLibraryLoader in an unnamed module (file:/home/marc/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/native-platform-0.22-milestone-26.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled
```

### Expected Behavior

No such warnings should be printed.

### Context (optional)

Configuring the `compileJava` task like this prevents the warning from being omitted:
```kotlin
tasks.compileJava {
    options.forkOptions.jvmArgs = listOf("--enable-native-access=ALL-UNNAMED")
}
```

Origin JEP: https://openjdk.org/jeps/472

### Self-contained Reproducer Project

1. Clone https://github.com/marcphilipp/gradle-sandbox
2. `cd gradle-jdk24-restricted-method-call-reproducer`
3. `./gradlew build --rerun-tasks`

### Gradle version

8.11.1

### Build scan URL (optional)

https://ge.junit.org/s/lfxtjzyxaqejw/console-log?task=:junit-platform-commons:compileJava

**Comment by lkasso** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by octylFractal** [comment]
I'll try to fix this in 8.14.

**Comment by big-guy** [comment]
We should fix this as part of supporting Java 24 (running Gradle and compiling/testing).

Workers and the Gradle daemon need to have this flag.

**Comment by sormuras** [comment]
For the record: https://youtrack.jetbrains.com/issue/IDEA-363985

**Comment by chrisgleissner** [comment]
I see that this has been closed and is part of release 8.14-rc1 as per this issue's milestone, however it still occurs  for me on, using Amazon Corretto 24.

Output of `./gradlew --version`:

```
./gradlew --version
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by net.rubygrapefruit.platform.internal.NativeLibraryLoader in an unnamed module (file:/home/chris/.gradle/wrapper/dists/gradle-8.14-rc-1-bin/ccmb0od6xb840t0y5am8hmj0t/gradle-8.14-rc-1/lib/native-platform-0.22-milestone-28.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled


------------------------------------------------------------
Gradle 8.14-rc-1
------------------------------------------------------------

Build time:    2025-04-09 08:46:50 UTC
Revision:      266969fceec7f1ad8c1d39e1354d963ce2857269

Kotlin:        2.0.21
Groovy:        3.0.24
Ant:           Apache Ant(TM) version 1.10.15 compiled on August 25 2024
Launcher JVM:  24 (Amazon.com Inc. 24+36-FR)
Daemon JVM:    /home/chris/.sdkman/candidates/java/24-amzn (no JDK specified, using current Java home)
OS:            Linux 6.11.0-21-generic amd64
```

Any ideas why this still occurs and in which Gradle release it will be fixed? 

Thanks

**Comment by octylFractal** [comment]
Have you run the `wrapper` task on 8.14 -rc-1? If you only ran `./gradlew wrapper --gradle-version=8.14-rc-1` once, due to a long-standing issue it won't have generated the wrapper scripts and JAR using the new version, so you'll need to run it again.

**Comment by chrisgleissner** [comment]
Thanks @octylFractal . I can confirm that the error disappeared after running `./gradlew wrapper`. I had already manually adjusted the Gradle version in the `./gradle/wrapper/.gradle-wrapper.properties` file. Thanks for your work to support Java 24, it is much appreciated.

**Comment by reidbaker** [comment]
This error message also appears even if you use `-q` which in theory is supposed to suppress warnings.

**Comment by octylFractal** [comment]
`-q` only affects Gradle's own warnings. These are logged by `java` directly to the original STDERR, so there is no suppression option for them.

**Comment by eygraber** [comment]
I'm still seeing this warning logged when using Java 24 even with Gradle 8.14

```
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by net.rubygrapefruit.platform.internal.NativeLibraryLoader in an unnamed module (file:/home/eli/.gradle/wrapper/dists/gradle-8.14-bin/38aieal9i53h9rfe7vjup95b9/gradle-8.14/lib/native-platform-0.22-milestone-28.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled
```

**Comment by specious** [comment]
What is the proper explanation for why the gradle wrapper needs to be used to regenerate the gradle wrapper after generating the gradle wrapper the first time?

**Comment by octylFractal** [comment]
See https://github.com/gradle/gradle/issues/884

**Comment by eygraber** [comment]
I'm seeing this again in 9.1.0-rc-2 (and I made sure the wrapper is generated correctly) in a project that provides a Gradle plugin.

```
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by net.rubygrapefruit.platform.internal.NativeLibraryLoader in an unnamed module (file:/home/eli/.gradle/wrapper/dists/gradle-9.1.0-rc-2-bin/aj5q5ib2t9qbe87h37b9y4lyg/gradle-9.1.0-rc-2/lib/native-platform-0.22-milestone-28.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled
```

This can be reproed in https://github.com/eygraber/release-tag-version-plugin

**Comment by octylFractal** [comment]
This is because your tests use Gradle TestKit, and therefore the Tooling API. You need to pass the appropriate option to the test workers via `Test.jvmArgs`.

**Comment by ZacSweers** [comment]
> You need to pass the appropriate option to the test workers via Test.jvmArgs.

@octylFractal shouldn't gradle just fix this? It's coming from gradle's own usage of it, which went unacknowledged here: https://github.com/gradle/native-platform/issues/343. I've found that `Test.jvmArgs` [doesn't actually appear to work anyway](https://github.com/ZacSweers/metro/commit/75745e53d48b50507ba4d35f361b8ba571cb4656)

**Comment by octylFractal** [comment]
I'm not sure what you mean, we did fix it for running Gradle itself, but we can't apply it to every Test task, as I don't believe we cause it in the Test task, as native platform isn't loaded there. If TestKit is used, then it does need to be applied, but driving that based on dependencies is significantly more involved.

If you're still seeing the warning and you're sure you haven't just missed updating the wrapper fully like above, please file an issue with a reproducer.

**Comment by ZacSweers** [comment]
I'm still seeing this in this project: https://github.com/zacsweers/metro with zulu JDK 24. Example scan: https://scans.gradle.com/s/3znfd7jlxlh3a/console-log?anchor=3182&page=4

The log pretty clearly indicates that gradle hasn't fixed this in the native platform library it embeds (which links back to here)

```
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by net.rubygrapefruit.platform.internal.NativeLibraryLoader in an unnamed module (file:/home/runner/.gradle/wrapper/dists/gradle-9.2.1-bin/2t0n5ozlw9xmuyvbp7dnzaxug/gradle-9.2.1/lib/native-platform-0.22-milestone-29.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled
```

Happy to revisit in that project's issue tracker if it's being maintained

**Comment by octylFractal** [comment]
Native platform doesn't have an issue here, it does need native access and won't be changed to remove that. If the Gradle daemon/wrapper is still emitting the warning, that is something we can fix as an issue in this project, by setting `--enable-native-access=ALL-UNNAMED` where necessary.

With your project, I set `--illegal-native-access=deny` on `Test`s and `JavaExec`s instead, and the stacktraces I got back were from `:gradle-plugin:functionalTest`, because of TestKit. Like I said previously, we don't want to apply `--enable-native-access=ALL-UNNAMED` to all `Test` tasks automatically (because in most cases, it's not necessary), but in your case you do need it applied. We don't have any plans to try and drive that based on the TestKit dependency right now, so you'll need to add it yourself. It might be a good idea to open an issue against the TestKit plugin you're using so it adds it for you.

I'm not sure why you think `jvmArgs` isn't working for you, it seems to be working fine from your scan, and from when I tried running your build. The scan you provided only contains a JMH warning, which is unrelated to us.

**Comment by ZacSweers** [comment]
I get it in just a typical build, separate from tests. That one happened to be running jmh tests.

>  it does need native access and won't be changed to remove that

The message is pretty clearly saying that it'll be blocked in the future, I'm not sure how you can avoid this?

**Comment by madisp** [comment]
@octylFractal this is more about native platform, but would it make sense to add `Enable-Native-Access: ALL-UNNAMED` to the jar manifest of the `native-platform` artifact?

**Comment by octylFractal** [comment]
> I get it in just a typical build, separate from tests. That one happened to be running jmh tests.

I'm not seeing that when I run `./gradlew build` locally on Java 25, aside from kotlin-compiler related ones which is also not related to us. Can you either provide a scan that does show one from native-platform, or provide clearer instructions on how to reproduce it?

> The message is pretty clearly saying that it'll be blocked in the future, I'm not sure how you can avoid this?

The message states it will be blocked "unless native access is enabled" -- that's what the flag does. We already set this for the [wrapper](https://github.com/gradle/gradle/blob/11bf60d04dbda61758f713dde586fbe95b72e037/platforms/core-runtime/wrapper-main/build.gradle.kts#L70-L71), [client](https://github.com/gradle/gradle/blob/11bf60d04dbda61758f713dde586fbe95b72e037/platforms/core-runtime/gradle-cli-main/build.gradle.kts#L34), and [daemon](https://github.com/gradle/gradle/blob/11bf60d04dbda61758f713dde586fbe95b72e037/platforms/core-runtime/client-services/src/main/java/org/gradle/launcher/daemon/client/DefaultDaemonStarter.java#L151), so we don't anticipate any problems.

> this is more about native platform, but would it make sense to add Enable-Native-Access: ALL-UNNAMED to the jar manifest of the native-platform artifact?

That doesn't work, it's only allowed to be used in an executable JAR, started with `-jar` (https://openjdk.org/jeps/472#Enabling-native-access). The "application" is the one that has to explicitly allow it, which we do as outlined above.
