### ISSUE TITLE
illegal reflective access

### ISSUE THREAD

**Issue by BruceEckel** [gradle/gradle#6204]
After upgrading to 4.9, I started getting the following during a build:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by worker.org.gradle.internal.reflect.JavaMethod (file:/C:/Users/Bruce/.gradle/caches/4.9/workerMain/gradle-worker.jar) to method java.lang.ClassLoader.getPackages()
WARNING: Please consider reporting this to the maintainers of worker.org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

To reproduce, clone 
https://github.com/BruceEckel/AtomicKotlinExamples
and run `gradlew test`

**Comment by oehme** [comment]
This is already fixed for 4.10, please try out the latest nightly.

**Comment by ber4444** [comment]
This is not fixed on 4.10, the error just changes to 
Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/x/.gradle/wrapper/dists/gradle-4.10-all/54ye4nru8k2rpf7xwj15he4fo/gradle-4.10/lib/groovy-all-2.4.15.jar) to method java.lang.Object.finalize()
from the previous
Illegal reflective access by worker.org.gradle.internal.reflect.JavaMethod (file:/home/x/.gradle/caches/4.9/workerMain/gradle-worker.jar) to method java.lang.ClassLoader.getPackages()

**Comment by ber4444** [comment]
Tried with 5.1.1 and 4.10.3 as well, with both of which the error message is no longer printed. The build itself still fails with the 
 Caused by: java.lang.NullPointerException
14:13:19.387 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:782)
like before but I guess that's a different issue to report to Google.

**Comment by TWiStErRob** [comment]
@ber4444 have you seen the linked https://github.com/gradle/gradle/issues/5529#issuecomment-411993552?
