### ISSUE TITLE
Gradle does not give an obvious error message when Maven credentials for maven-publish are null

### ISSUE THREAD

**Issue by shindouj** [gradle/gradle#6369]
### Expected Behavior
Gradle notifies the developer that Maven credentials are wrong, e.g. "Wrong Maven credentials (null value provided).

### Current Behavior
Gradle returns a very confusing error message:

`Failed to retrieve remote metadata net.jeikobu:jbase:1.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata net.jeikobu:jbase:1.0-SNAPSHOT/maven-metadata.xml from/to remote (https://repo.url/): Could not get resource 'net/jeikobu/jbase/1.0-SNAPSHOT/maven-metadata.xml'`

Upon further inspection (preferrably through a Gradle Scan), a NullPointerException can be found:

(...)
Caused by: java.lang.NullPointerException: (No message provided)
   at org.gradle.internal.resource.transport.http.ntlm.NTLMCredentials.<init>(NTLMCredentials.java:35)
(...)

### Context
I was trying to use TeamCity's properties and misconfigured them. If not for Gradle Scan, I would still be looking for a solution, because I would never find this exception in debug logs.

### Steps to Reproduce
* Configure a project with maven-publish
* Provide null in place of credentials
* Execute gradle publish

### Your Environment
I think this is platform-dependless, but I reproduced that behaviour successfully on both TeamCity 2018.1 running in Linux Docker and on Windows 10 1803 Pro, running Gradle 4.4 and 4.9 wrapper (can reproduce on both).

* Build scan URL: https://scans.gradle.com/s/mxoloozq3qs3i/

**Comment by marcphilipp** [comment]
Thanks for the bug report. I agree that it should throw a more meaningful exception than an NPE. Instead, `NTLMCredentials` should check that `username` is not null and throw an `IllegalArgumentException` with a `"Username must not be null"` message.

@shindouj Do you have time to submit a PR?

**Comment by marcphilipp** [comment]
Resolved in #6379.

**Comment by feldman10** [comment]
I have a Username must not be null! but I don`t know where I am missing the user name, so i thing it may be more specific

**Comment by kevgilmore** [comment]
This is still an issue for me.
> Username must not be null!

Even though I have `ARTIFACTORY_USER` set
