### ISSUE TITLE
User Manual in PDF format has broken links

### ISSUE THREAD

**Issue by thc202** [gradle/gradle#6546]
The [User Manual in PDF format](https://docs.gradle.org/current/userguide/userguide.pdf) (Version 4.10) has relative links when linking to JavaDoc and DSL, e.g.:
 - `../javadoc/org/gradle/api/tasks/testing/Test.html#setMaxParallelForks-int-`
 - `../dsl/org.gradle.api.tasks.compile.JavaCompile.html`

Some links in tables were not properly converted, e.g:
 - `@link:{javadocPath}/org/gradle/api/tasks/Input.html[Input]`
 - `<<#sec:task_input_using_classpath_annotations,Using the classpath annotations>>`

This also happens with PDF generated from master branch.

Let me know if I need to provide more information.

**Comment by eriwen** [comment]
Fixed by b9f43722b8f17cf2a89bc21453a97a510c614ea5

**Comment by thc202** [comment]
@eriwen thanks! The issue in the tables is not yet fixed, should I raise an issue specifically for that or you already tracking it?

**Comment by eriwen** [comment]
You're right. I fixed a different issue instead.

**Comment by LarsKaulen** [comment]
When looking at the [current userguide](https://docs.gradle.org/current/userguide/userguide.pdf) (e.g. at Table 1) the issues in the tables seem to be fixed. There were no changes in the asciidoc-files regarding these issues, so it seems to be caused by changes in the asciidoc-to-pdf engine, although I couldn't track down which changes exactly fixed it.

**Comment by thc202** [comment]
Indeed, thanks for the heads up! Closing.
