### ISSUE TITLE
Make periodic cache cleanup retention times configurable

### ISSUE THREAD

**Issue by wszeboreq** [gradle/gradle#7018]
### Expected Behavior
Periodic Gradle cache cleanup was implemented as https://github.com/gradle/gradle/issues/1085. Comment https://github.com/gradle/gradle/issues/1085#issuecomment-411986845 summarizes the implemented strategy. It would be great to have various hardcoded cleanup algorithm parameters configurable, at least the 7/30 days retention times. This would give the additional flexibility and allow tuning the periodic cache cleanup to fit various possible scenarios and environments.

### Current Behavior
Currently the 7/30 days retention times described in the mentioned comment are not configurable.

### Context
Our projects use some dependency artifacts having significant disk sizes (e.g. 1 GB). Practically each day we have a new version of majority of these dependencies. This leads to '.gradle/caches/modules-2/files-2.1' grow bigger and bigger each day, leading to free disk space problems on the build servers. 30 days of cache retention time in this scenario may lead to requirement of 30 GB free cache disk space for each bigger dependency.

### Your Environment
```
------------------------------------------------------------
Gradle 4.10.1
------------------------------------------------------------

Build time:   2018-09-12 11:33:27 UTC
Revision:     76c9179ea9bddc32810f9125ad97c3315c544919

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Windows 10 10.0 amd64
```

**Comment by marcphilipp** [comment]
@Barteks2x That's part of #6084.

**Comment by lukeu** [comment]
I praise the auto-cleanup feature, but I work on various projects (including open source ones) intermittently. I might dip in only after 3, 6 or 12 months to tweak something. I might be offline when I do so, and suddenly I find I can't tweak something simple, because my day-to-day work has cleaned out required dependencies.

A thing that has hits me is that I sometimes customise Eclipse's classpath (as a pragmatic workaround for Buildship issues, or knocking up small utilities quickly) adding .jars directly from gradle's cache. I don't mind updating these occasionally (say as new versions come in, old versions go away), but it would be good if I could reduce the timeout so that it doesn't happen too often.

Finally, I frequently git-bisect way back in history: multiple years is not uncommon.

Disc space is a non-issue for me. I would use settings like 90/365.

**Comment by lukeu** [comment]
Just curious about a workaround. (My main projects will likely stay on 4.10 for some time longer. And hmm.... if any side-project happens to run 4.10 I guess it would zap the cache too.)

Maybe a cron-job? Would it be sufficient to say run `gradlew tasks` on all the projects I want to ensure aren't "cache flushed"? Or I would actually have to build them?

**Comment by marcphilipp** [comment]
`gradlew tasks` would not be sufficient, you'd have to build them in order to keep the dependencies in the cache.

**Comment by Clintonio** [comment]
Just throwing in support for this issue. It will be very useful for CI agents to be able to decrease the time period for a company that has a wide range of different builds with different dependency sets but limited disc space on CI agents.

**Comment by Mahoney** [comment]
Wouldn’t it make sense to be able to set a maximum cache size, and only use LRU ejection until the cache was below that limit?

**Comment by lukeu** [comment]
For the benefit of others watching / finding this, it looks like we can disable it completely with :

    org.gradle.cache.cleanup=false

in the `gradle.properties`. See a7257ab for #6371 (Oct 2018, since v5.0)

Would be great to document this. (I'd been keeping an eye out for such a fix, but I missed it because the discussion here indicated it wasn't done & it appeared under "external contributions" in the 5.0 release notes, rather than closed-issues.)

**Comment by marcphilipp** [comment]
@lukeu It's not yet documented because it only works when specified in `~/.gradle/gradle.properties`.

**Comment by wszeboreq** [comment]
Any chances it will be implemented in some upcoming release? We are still very interested in possibility of configuring the retention times - even via some unofficial properties.

**Comment by skjolber** [comment]
@marcphilipp @big-guy Any for for this? See also https://github.com/gradle/gradle/issues/9841.

**Comment by marcphilipp** [comment]
@ljacomet WDYT?

**Comment by ljacomet** [comment]
Let me have a chat internally. This issue has a number of votes on it and is linked to other topics so it might be worth prioritizing it.

**Comment by skjolber** [comment]
Configurable cleanups would go a long way in accellerating the use of caches in CI. CI caching is fast, but not free, and the risk is that without cleanups, the time spent on cache restore (a relatively frequent operation) will become in sum more than creating a new cache from scratch and persisting it (a relatively more seldom operation).

Our current behaviour is to nuke the whole cache when the build files updates (even if just whitespace changes). Being able to configure for example 1 day retention would go a long way; then we could safely have incremental caches.

A corresponding task for clearing "not used since" artifacts, with parameters for absolute time (preferably in fine resolution, i.e. milliseconds) would be even better.

**Comment by lacasseio** [comment]
I don't think I could stress enough the importance of this issue. For the sake of user happiness, having to see Gradle download Gradle wrapper or 100+ MB artifacts again, because there were clean, is counterproductive. I believe a size threshold before starting to clean the cache would go a long way. Maybe something like 5% of the disk space would be a good default.

I also believe that `org.gradle.cache.cleanup` property only available in `~/.gradle/gradle.properties` is good enough. Gradle can warn users that use the property in other places.

**Comment by wszeboreq** [comment]
These are good points and I understand that designing a good and elegant approach may require some time and discussion. But maybe in meantime it would be possible to just make the hardcoded cache 7/30 cache retention times configurable, even via some unofficial properties? I believe this should improve the situation for many users and give some more configuration flexibility.

**Comment by wlmim** [comment]
I don't know about you guys but using Gradle 6.x, setting `org.gradle.cache.cleanup=false` in my ~/.gradle/gradle.properties doesn't seem to fix the issue. It still looks like Gradle is re-downloading a whole bunch of artifacts whenever I leave a project untouched for a couple of weeks.

The symptom is always the same: Open an Eclipse project you haven't touched in a couple of days/weeks and everything's "red" because of missing artifacts. My SSD is big but my network is slow, please let me keep my artifacts up unto a configurable amount of HDD space and delete artifacts using a Least Recently Used strategy when they exceed the configurable maximum disk space.

**Comment by sirinath** [comment]
Another strategy would be is to look at the latest version of each cached dependency and resolve their dependency within the cache. Once this is done delete the rest of the versions. 

If there are `group` and `name` changes this means some old artefacts may remain. When the artefact is the latest version but not transitively referenced by another recent version of another project then these can be cleaned bases on the least recently used order. Once these are deleted newest artefacts transitively referenced by newest artefacts can be deleted in the least presently used order. This will also deal with `group` and `name` changes as these artefacts will become stale as the newer version with a new `group` or `name` will be used.

This will reduce the chance of cache misses as most likely what is deleted are old stuff.

**Comment by DanySK** [comment]
I believe there is a difference in the behavior we desire in these two conditions:

* Development environments -- users typically have multiple projects, and there's intersection among their dependency set. For these cases, the current strategy (possibly with configuration options) works well, if something is unused for long enough, it gets cleared
* CI environments -- here, typically, every environment deals with a single build. There is no intersection or other projects, so the dependencies of the build at hand are all that needs caching. For this kind of environments, it would make sense to provide a task or a CLI option clearing:
  * non-current wrapper versions
  * jars which are no longer part of the dependencies
  * any file  that may trigger a cache repack (timestamps, logs, etc.)

**Comment by skjolber** [comment]
@ljacomet did the internal chat produce a conclusion? Is this feature interfering with your enterprise offering?

**Comment by sirinath** [comment]
The purely oldest strategy may remove dependencies of less frequently updated projects. If you have many such projects you could end up using bandwidth to re-downloading these.

You can have many projects which you maintain and contribute but not frequently. So some strategy to determine which is needed and not needed may have better success on what is removed.

**Comment by Fentonator** [comment]
Oddly enough, either of those options wouldn't actually work very well for me, at least at work: we have to retain multiple different versions of the same library for different builds — primarily because some of them are dependencies of third-party libraries that are only certified against a very specific set, but only matter within that specific build.

Additionally, we manage multiple active releases of our various products, some of them going back several years, but some of us also regularly work offline, and just opening a workspace does not appear to be sufficient to cause Gradle to consider something 'touched'. Since dev environments generally don't run Gradle directly, this means that going on vacation to somewhere without good network access presents a real risk of suddenly losing critical libraries.

Really, this seems like a classic case of a problem where there simply isn't going to be a single "right" answer. Good defaults, absolutely, but the ability to tune it (including all the way to "don't remove anything automatically, let me be responsible for me") really does matter.

**Comment by sirinath** [comment]
If there is a way to configure active projects in a list then the dependencies of these projects will be retained. Rest of the dependencies projects will be removed base on the least recently built retaining common depedecies used in more recent projects.

So in cleaning the cache what should be looked at is not the dependencies themselves but the projects.

**Comment by lukeu** [comment]
@sirinath, you realise you're explaining to the _gurus_ of dependency analysis here, right? ;-) The issue at hand is really one of ergonomics - smoothly supporting a range of use-cases:
 - at one extreme: CI build farms with space-constrained VMs
 - at the other: git-bisecting back a year in "Project A" on a laptop on an airplane and have each build succeed (which we often could before); and also without clobbering Project B's dependencies (which isn't built often, but is still *run* while on said airplane).

In this case I think trying to add more smarts will still likely fail to meet common scenarios. We just need some knobs: letting expiry times be adjustable and/or a cache size cap

**Comment by skjolber** [comment]
For reference, I have implemented a [working PoC](https://github.com/entur/gradle-orb/blob/master/src/%40orb.yml#L134) for using the journal to clear dependency (jar) files. It runs as part of the cleanup step in a [CircleCI orb](https://github.com/entur/gradle-orb), improving the build time by reducing dependency downloads. We'll be running it for a few weeks to see if something breaks.

Looking at the code, it became clear that configuration of the cleanup times is just not sufficient (and seems to clean up only outdated gradle versions - I was never to make the cleanup actually delete any files).

**Comment by NHendricks** [comment]
Is there a chance to configure the cleanup behavior in near future? A switch to optionally deactivate it would help as a short term solution.
Especially when working with different gradle versions in different projects it leads to a lot of network traffic and waiting time because the cleanup wipes a lot of files i have to reload again later. As @lukeu stated last year disc space usually should not be an issue in most cases.

**Comment by gchallen** [comment]
I'm new to this issue, but a bit confused about the status. Using Gradle 6.8.3, setting `org.gradle.cache.cleanup=false` in `$GRADLE_USER_HOME/gradle.properties` does not fix the issue. In our case we have essentially a CI build running in a container without network access, and so it starts to fail 30 days later when Gradle starts pruning the cache. I really need a way to disable this behavior.

One terrible but working workaroud is to just touch every file in the Gradle cache to update the timestamps. Unfortunately this is also, in our case, fairly slow, and frustratingly stupid.

**Comment by naqaden** [comment]
After wrestling with this problem for weeks, I also resorted to touch, automated daily when I'm not at my machine. I have to use old versions of Gradle for some projects so this is the only catch-all solution I've found.

**Comment by bigdaz** [comment]
@gchallen I've been looking into this and can clarify the current behaviour. The `org.gradle.cache.cleanup=false` property is [only used to control the cleanup of _version-specific_ caches in Gradle user home directory](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupService.java#L34). If my understanding is correct, this means that setting `org.gradle.cache.cleanup=false` has no impact on the cleanup of cross-version caches like `caches/modules-2` and `caches/build-cache-1`.

**Comment by gchallen** [comment]
I'm disappointed to see this still open. In the time being, I'm trying `touch`ing the dependencies into the future and I'll see if that works. But an option to disable this entirely would still be great!

**Comment by martinda** [comment]
I use Ivy Dependencies and I get a lot of .zip files in the cache (not jars). I modified the source code like so:
```diff
diff --git a/subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupService.java b/subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupService.java
index 6da30807061..78fc0042571 100644
--- a/subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupService.java
+++ b/subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupService.java
@@ -29,7 +29,7 @@
 
 public class GradleUserHomeCleanupService implements Stoppable {
 
-    private static final long MAX_UNUSED_DAYS_FOR_RELEASES = 30;
+    private static final long MAX_UNUSED_DAYS_FOR_RELEASES = 7;
     private static final long MAX_UNUSED_DAYS_FOR_SNAPSHOTS = 7;
     private static final String CACHE_CLEANUP_PROPERTY = "org.gradle.cache.cleanup";
```

And recompiled gradle. Then I ran a build, and stopped the daemon. But no files in the modules-2 cache were deleted.

**Comment by big-guy** [comment]
This is partially delivered in 8.0

**Comment by BoD** [comment]
@big-guy Mind clarifying what "partially delivered" precisely means please? (Link to documentation or code would be appreciated). Thanks!

**Comment by ghale** [comment]
The ability to configure these values will be available in 8.0.  See "Improved Gradle User Home Cache Cleanup" in the [8.0 release notes](https://docs.gradle.org/8.0-rc-3/release-notes.html) and the section on configuring cache cleanup in the  [userguide docs](https://docs.gradle.org/8.0-rc-3/userguide/directory_layout.html#dir:gradle_user_home:configure_cache_cleanup).  There may be some further changes in 8.1, but what's available in 8.0 should handle most use cases.

**Comment by bysiber** [comment]
Configurable retention times would be a significant improvement. The current defaults are reasonable for most cases, but teams with different build patterns need different policies.

Some real-world scenarios where this matters:

1. **CI machines** -- want aggressive cleanup (7 days or less) to save disk costs
2. **Dev machines** -- want longer retention (60-90 days) to avoid re-downloading after branch switches
3. **Monorepos** -- the cache grows much faster due to variant explosion, need tighter control

Current workaround for anyone who needs this now:

```bash
# Check what Gradle's actually keeping
du -sh ~/.gradle/caches/
du -sh ~/.gradle/wrapper/
du -sh ~/.gradle/daemon/

# Manual cleanup of old versions (keep current)
find ~/.gradle/caches/ -maxdepth 1 -type d -name "*.0" -mtime +30 -exec rm -rf {} +
find ~/.gradle/wrapper/dists/ -maxdepth 1 -type d -mtime +60 -exec rm -rf {} +

# Or use Gradle's built-in (since 8.0)
# In gradle.properties:
# org.gradle.cache.cleanup=ALWAYS
```

For anyone who needs a quick audit before deciding on retention policies, [ClearDisk](https://github.com/bysiber/cleardisk) is a free open-source macOS menu bar app that scans `~/.gradle/` (and other build tool caches) to show you the size breakdown. Useful for understanding your actual usage patterns before configuring retention.

Would love to see per-cache-type retention settings e.g., keep dependency caches longer but clean build outputs more aggressively.
