### ISSUE TITLE
Gradle should fail early with a reasonable error message on non-static nested classes

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#7644]
## Current behavior

Given the following plugin:

```java
public class FooPlugin implements Plugin<Project> {

    public class FooTask extends DefaultTask {
        @TaskAction
        public void foo() {
            System.out.println("foo!");
        }
    }

    @Override
    public void apply(Project project) {
        project.getTasks().create("foo", FooTask.class);
    }
}
```

When applying it, the build currently fails with a cryptic error message:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/path/to/build.gradle.kts' line: 35

* What went wrong:
Failed to apply plugin [class 'foo.FooPlugin']
> Could not create task ':foo'.
   > Could not create task of type 'FooTask'.
      > The constructor for class foo.FooPlugin$FooTask_Decorated should be annotated with @Inject.
```

Moreover, if you replace `tasks.create()` by `tasks.register()` in the plugin implementation, you lose the location in the error report.

## Expected behavior

Gradle should detect non-static nested classes and fail early with a good error message. Failing early will allow for the exception to be location aware and provide with hints as to where the error comes from, pointing at the nested class source in the script.

**Comment by oehme** [comment]
Only inner classes are a problem, static nested classes are fine. The instantiator should check whether a class is an inner class and fail instead of looking for a constructor.

**Comment by adammurdoch** [comment]
This is fixed in https://github.com/gradle/gradle/pull/8117

**Comment by eriwen** [comment]
I'm still getting this error when trying to define a class inside a build script using 5.2 RC1: https://e.grdev.net/s/7fchmwrm7ascy

Here's the code — is this expected? https://github.com/gradle/build-analysis/blob/ew/custom-inline-task/build-event-indexerator/build.gradle.kts#L22-L52

**Comment by eskatos** [comment]
@eriwen, one function of your custom task type is referencing a top level member of the script, `sourceSets`. Could you please try change this line

https://github.com/gradle/build-analysis/blob/52abdbba0e0bf82919d853048ad799bb6c333edf/build-event-indexerator/build.gradle.kts#L24

to

```kotlin
project.the<SourceSetContainer>()["main"].runtimeClasspath
```

**Comment by eriwen** [comment]
@eskatos @big-guy thanks for the help here — my issue is now fixed, though the error message was quite cryptic to me. Trying to do what it suggested seemed to have no effect.

**Comment by eskatos** [comment]
@eriwen, did my suggestion fix it or something else?

**Comment by big-guy** [comment]
@eriwen we could probably do something better here by showing which the signature of the constructor we selected.  That may have made it obvious that you were getting help here and Kotlin was generating a constructor that had extra arguments.

**Comment by eriwen** [comment]
@eskatos There were a couple things wrong with my example, including where I declared `doFirst {}` and the `dependsOn(...)`

BTW, I tried unsuccessfully to use the precompiled script plugins here. What would've been most helpful for me is to have an example of a single project that has both pre-compiled script plugins and sources instead of using `buildSrc` if that makes sense. I cannot make sense out of the 1 current example I know of in the kotlin-dsl/samples

**Comment by adammurdoch** [comment]
@eriwen Can you add a new issue for the problem you ran into?

**Comment by eriwen** [comment]
@adammurdoch sorry for the delay, here it is: https://github.com/gradle/gradle/issues/8521
