### ISSUE TITLE
Tooling API on JDK11 can not connect to Gradle project 4.5

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#8431]
When trying to obtain a model using `org.gradle.tooling.ModelBuilder.get()` (Gradle Tooling API v4.10.3, running on JDK 11)  from a project with Gradle Wrapper 4.5, an exception is thrown. See full stacktrace below

Possibly, a re-open of https://github.com/gradle/gradle/issues/3317
Related fix https://github.com/gradle/gradle/pull/3403/files#diff-43bde79c2779f0e0cc404437d062bd67R31

### Expected Behavior
Model should be obtained successfully

### Current Behavior
Exception is thrown

### Context
Import a Gradle project (wrapper, 4.5) into Intellij IDEA running on java v 11

### Steps to Reproduce (for bugs)
n/a

### Your Environment
n/a

**Comment by nskvortsov** [comment]
org.gradle.tooling.GradleConnectionException: Could not create an instance of Tooling API implementation using the specified Gradle distribution 'https://services.gradle.org/distributions/gradle-4.5-bin.zip'.
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.create(DefaultToolingImplementationLoader.java:114)
	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:44)
	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:43)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:101)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultModelBuilder.get(DefaultModelBuilder.java:50)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.getBuildEnvironment(GradleExecutionHelper.java:573)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.getBuildEnvironment(GradleExecutionHelper.java:85)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.doResolveProjectInfo(GradleProjectResolver.java:183)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.access$200(GradleProjectResolver.java:75)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:739)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:722)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.execute(GradleExecutionHelper.java:223)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:140)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:75)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.lambda$resolveProjectInfo$0(RemoteExternalSystemProjectResolverImpl.java:36)
	at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:57)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:36)
	at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:44)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:99)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:165)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:151)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.executeImpl(ExternalSystemUtil.java:559)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.lambda$execute$0(ExternalSystemUtil.java:399)
	at com.intellij.openapi.project.DumbServiceImpl.suspendIndexingAndRun(DumbServiceImpl.java:146)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:399)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$5.run(ExternalSystemUtil.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.gradle.internal.service.ServiceCreationException: Could not create service of type FileMetadataAccessor using NativeServices.createFileMetadataAccessor().
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:857)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:808)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:612)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:669)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:821)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:807)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:612)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:669)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:821)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:807)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:612)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:669)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:821)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:807)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:612)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:669)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:821)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:807)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:612)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:669)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:821)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:807)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:612)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:669)
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:322)
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:316)
	at org.gradle.tooling.internal.provider.DefaultConnection.initializeServices(DefaultConnection.java:125)
	at org.gradle.tooling.internal.provider.DefaultConnection.configure(DefaultConnection.java:102)
	at org.gradle.tooling.internal.consumer.connection.AbstractPost12ConsumerConnection.configure(AbstractPost12ConsumerConnection.java:37)
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.createConnection(DefaultToolingImplementationLoader.java:119)
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.create(DefaultToolingImplementationLoader.java:95)
	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:44)
	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:43)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:101)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	... 1 more
Caused by: java.lang.IllegalArgumentException: Could not determine java version from '11-internal'.
	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:72)
	at org.gradle.api.JavaVersion.current(JavaVersion.java:82)
	at org.gradle.internal.nativeintegration.services.NativeServices.createFileMetadataAccessor(NativeServices.java:253)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:855)
	... 44 more

**Comment by oehme** [comment]
The test coverage stopped at Gradle 4.2, so this old problem was reintroduced in later 4.x releases. Essentially, any time `JavaVersion` is used in the provider part of the TAPI client, it needs to be protected or otherwise it will crash the TAPI on newer Java versions.

**Comment by oehme** [comment]
This was fixed in Gradle 4.7, so one solution could be to inform users that they'll need to upgrade to a fixed version. Upgrading within the 4.x stream should be low-impact.

**Comment by nskvortsov** [comment]
ok, so now we have a case of a project with Gradle 2.9 configured to run using installed JDK 1.8 (which should succeed) fails to import in IDEA with JDK11 runtime.

**Comment by annablog** [comment]
Was directed here from an error message in the latest version of IntelliJ (2019.2).

What's the solution for those of us who are forced to work with an earlier version of gradle? For now I'm reverting back to 2019.1, but will this mean we can't use any future versions of IntelliJ?

**Comment by goodspb** [comment]
@annablog same problem for me in the latest version of  IntelliJ.

**Comment by yfccc** [comment]
@annablog ctrl+shift+a -> Switch Boot JDK ->choose version ……

**Comment by annablog** [comment]
@yfccc Seems to work so far, thanks for the suggestion. Tried the Java that was bundled with 2019.1.4 of IntelliJ. I didn't realise that IntelliJ had its own version of Java bundled with it.

@goodspb : See above for a workaround.

**Comment by lycwahaha** [comment]
> @annablog ctrl+shift+a -> Switch Boot JDK ->choose version ……

idea 2019.02开始居然自带jdk11，jdk11和gradle 2.x都不支持（看这里好像是4.5以前都不支持）坑爹啊。给大佬点个赞👍👍👍
Transalation: idea 2019.02 itself uses jdk11, which is incompatible with gradle 2.x (and here it seems unfriendly to version older than 4.5). Thumbs up👍👍👍

**Comment by goodspb** [comment]
@yfccc But if I switch boot jdk to jdk8, the idea wil boot as defalut jvm, not openJDK vm. so, you know, the font will be ugly. 

Eventually , I just download another version of 2019.02（with bundled JBR 8）than everything is fine.

https://www.jetbrains.com/idea/download/other.html

**Comment by Adaaaagio** [comment]
> @annablog ctrl+shift+a -> Switch Boot JDK ->choose version ……

it works! thanks!

**Comment by mcpower** [comment]
Regarding the problem in IntelliJ: I fixed the problem with a combination of @yfccc and @goodspb's workarounds. You can install JBR 8 in an IntelliJ bundled with JBR 11 by following these steps in the IntelliJ documentation - no need for reinstallation: https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

**Comment by sxp4820** [comment]
> https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

![图片](https://user-images.githubusercontent.com/59801556/72399128-2be52300-3780-11ea-8f65-e76f4fc9b9df.png)


**All platforms: download and install JetBrains Runtime via Choose Runtime plug-in**

    1. Install the Choose Runtime plugin (screenshot).

    2. Start the IDE, use Help | Find Action (Ctrl+Shift+A or Cmd+Shift+A on Mac), type "Choose Runtime", press Enter.

    3. Select the version to install, the higher the number after b, the more recent is the version. It makes sense to install the most recent version or the version you were asked to try by JetBrains staff. Installing old runtime versions may render your IDE unusable or introduce new issues.

    4. Click the Download button and wait until the file with JetBrains Runtime is downloaded.

    5. Once download is finished, click the Install button, the file will be unpacked into idea.config.path\jdks location and the full path to this JDK will be saved into idea.config.path\<product>.jdk file, for example: C:\Users\serge\.IntelliJIdea2017.1\config\jdks\jbsdk8u152b819.1_windows_x64. IDE will automatically restart.

    6. Verify via About dialog that the new runtime is used. Notice the vendor (should be JetBrains s.r.o) and the release number (should correspond to the number after b in the file you've downloaded).

    7. If the JDK version in the About dialog doesn't match or didn't change, see below. Most likely, you have an environment variable configured which has the priority over the <product>.jdk file. Remove any environment variables affecting IDE runtime selection and restart.

**Comment by donat** [comment]
@big-guy the problem still persists with the latest Tooling API client. What surpises me is that our cross-version tests don't fail for this scenario.

**Comment by donat** [comment]
Our test coverage contains tests only where the Tooling API (TAPI) and the Gradle daemon runs on the same JDK version. Also, our tests are [constrained](https://github.com/gradle/gradle/blob/a68c98a5b207970c60d6c08a5ffea83e0e353010/subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/DefaultGradleDistribution.java#L102) such that testing older Gradle versions on Java 11 is ignored. The combination of these two things is the reason why we missed this use-case.

**Comment by donat** [comment]
We did some further investigation with @big-guy and found that the situation is a bit tricky. The problematic `JavaVersion` class is loaded by TAPI from the Gradle daemon and initialized on the TAPI JVM causing the error. Now, what's interesting, that the error happens on the provider side, ultimately leading to an exception on the provider-side.
```
Caused by: org.gradle.internal.service.ServiceCreationException: Could not create service of type JvmVersionDetector using BasicGlobalScopeServices.createJvmVersionDetector().
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:857)
...
at org.gradle.tooling.internal.provider.DefaultConnection.initializeServices(DefaultConnection.java:125)
	at org.gradle.tooling.internal.provider.DefaultConnection.configure(DefaultConnection.java:102)
	at org.gradle.tooling.internal.consumer.connection.AbstractPost12ConsumerConnection.configure(AbstractPost12ConsumerConnection.java:37)
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.createConnection(DefaultToolingImplementationLoader.java:104)
```

/cc @ljacomet @adammurdoch

**Comment by donat** [comment]
If IntelliJ will switch to Java 11 by default, it won't be able to import any projects using Gradle <4.8, so the impact is quite big.

**Comment by vfedoriv** [comment]
And now IntelliJ 2020.1 switched to Java 11, no variants with JBR 8.

**Comment by lycwahaha** [comment]
> > @annablog ctrl+shift+a -> Switch Boot JDK ->choose version ……
> 
> idea 2019.02开始居然自带jdk11，jdk11和gradle 2.x都不支持（看这里好像是4.5以前都不支持）坑爹啊。给大佬点个赞👍👍👍
> Transalation: idea 2019.02 itself uses jdk11, which is incompatible with gradle 2.x (and here it seems unfriendly to version older than 4.5). Thumbs up👍👍👍

最新2020版本强制不能使用gradle 2了，太坑

**Comment by nskvortsov** [comment]
We are receiving some feedback for Idea 2020.1 https://youtrack.jetbrains.com/issue/IDEA-237220

**Comment by nskvortsov** [comment]
According to our stats, around 12% of Gradle-based projects still use version <4.8 and are affected by this problem. While it is possible to run IDEA 2020.1.1 using runtime 1.8 as a workaround, it will not be in 2020.2

**Comment by axlmly** [comment]
I also had this problem, and I spent two days and two nights checking it out.

**Comment by fozersahin** [comment]
For switching - > https://www.jetbrains.com/help/idea/switching-boot-jdk.html

**Comment by merc-angel** [comment]
Problem still occurs with Java 11.

**Comment by donat** [comment]
This should be fixed by #14444

**Comment by praveen12bnitt** [comment]
@nskvortsov  given that this issues is fixed, can we make adopt this to intellij and allow gradle projects < 4.5 to be imported successfully?

**Comment by nskvortsov** [comment]
@praveen12bnitt we will definitely be adopting this to IntelliJ in next major release 2020.3

**Comment by s2it-lsouza** [comment]
**I got this error using Intellij 2020.2.2, gradle 5.6.4, jdk11**

Could not unzip /home/luiz/.gradle/wrapper/dists/gradle-5.6.4-bin/a2900rtbjbwr4ya1p11l7095t/gradle-5.6.4-bin.zip to /home/luiz/.gradle/wrapper/dists/gradle-5.6.4-bin/a2900rtbjbwr4ya1p11l7095t.
Reason: zip END header not found
Exception in thread "main" java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1567)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1462)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1469)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
        at org.gradle.wrapper.Install.unzip(Install.java:218)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

When I've changed Intellij to version 2020.2.1, the build works fine.

**Comment by praveen12bnitt** [comment]
@nskvortsov i upgrade to Idea 2020.3 today and my project using gradle 2.14 is still having the same error message.


Cannot determine classpath for resource 'java/sql/SQLException.class' from location 'jrt:/java.sql/java/sql/SQLException.class'.

The project uses Gradle 2.14.1 which is incompatible with IDEA running on Java 10 or newer.
See details at https://github.com/gradle/gradle/issues/8431
Possible solution:
 - Upgrade Gradle wrapper to 4.8.1 version and re-import the project

**Comment by nskvortsov** [comment]
@praveen12bnitt 
This change did not made it to first EAP of IDEA 2020.3, please stay tuned. Also, please note compatibility is restored up to Gradle 3.0+ 

Gradle 2.14.1 is not working at the moment.

**Comment by praveen12bnitt** [comment]
thanks. I am eagerly waiting for this. I can upgrade to 3.0 . So that should be fine.

**Comment by Manish-Bannur** [comment]
After Gradle wrapper upgraded to 4.8.1.
Error - Could not initialize class com.android.sdklib.repository.AndroidSdkHandler

**Comment by adarshrc** [comment]
same problem here !

> @nskvortsov i upgrade to Idea 2020.3 today and my project using gradle 2.14 is still having the same error message.
> 
> Cannot determine classpath for resource 'java/sql/SQLException.class' from location 'jrt:/java.sql/java/sql/SQLException.class'.
> 
> The project uses Gradle 2.14.1 which is incompatible with IDEA running on Java 10 or newer.
> See details at #8431
> Possible solution:
> 
> * Upgrade Gradle wrapper to 4.8.1 version and re-import the project

how to resolve it ?

**Comment by nskvortsov** [comment]
@adarshrc please upgrade your Gradle wrapper to at least version 3.0 (or better to 4.8.1, as error message suggests)
